import type { Level, NarrationLine } from './course-data';

/**
 * Hand-authored listening scripts, one per item.
 *
 * These replace the generated listening pool, where 416 items were rotations of
 * about 60 template scripts — the narration *is* the tested content in 聴解, so a
 * template with the nouns swapped is the same question asked again. Every script
 * here is distinct: its own situation, its own speakers and its own answer.
 *
 * Conventions:
 *  - `options[0]` is always the correct answer; the app shuffles at render.
 *  - 概要理解 must set `revealAfterAudio`: the real item type gives no question
 *    before the audio plays.
 *  - 発話表現 shows a picture, so its scenes are written to fit one of the four
 *    illustrations the app actually has.
 */
export type Script = {
  jp: string;
  itemType: string;
  prompt: string;
  narration: NarrationLine[];
  options: string[];
  note: string;
  image?: string;
  imageAlt?: string;
  revealAfterAudio?: boolean;
};

const SHOP = { image: '/irasutoya-shopping.png', imageAlt: 'A family shopping at a supermarket' };
const MEET = { image: '/irasutoya-meeting.png', imageAlt: 'Colleagues talking in an office' };
const STATION = { image: '/irasutoya-station-staff.png', imageAlt: 'A station employee helping a passenger' };
const WEATHER = { image: '/irasutoya-weather.png', imageAlt: 'A weather forecaster pointing at a map' };

const task = (jp = '課題理解') => ({ jp, itemType: 'Task comprehension' });
const point = (jp = 'ポイント理解') => ({ jp, itemType: 'Point comprehension' });
const quick = (jp = '即時応答') => ({ jp, itemType: 'Quick response' });
const speech = (jp = '発話表現') => ({ jp, itemType: 'Verbal expressions' });
const summary = (jp = '概要理解') => ({ jp, itemType: 'Summary comprehension' });
const integrated = (jp = '統合理解') => ({ jp, itemType: 'Integrated listening' });

const n5: Script[] = [
  /* ---------- 課題理解 ---------- */
  {
    ...task(), ...SHOP,
    prompt: 'おんなの人は　この　あと　まず　何を　しますか。',
    narration: [
      { speaker: 'narrator', text: 'スーパーで　おんなの人と　おとこの人が　はなしています。おんなの人は　この　あと　まず　何を　しますか。', pauseAfter: 700 },
      { speaker: 'a', text: 'ぎゅうにゅうと　パンを　かいましょう。', pauseAfter: 300 },
      { speaker: 'b', text: 'パンは　いえに　ありますよ。', pauseAfter: 300 },
      { speaker: 'a', text: 'そうですか。じゃあ、ぎゅうにゅうだけ　かいます。', pauseAfter: 600 },
      { speaker: 'narrator', text: 'おんなの人は　この　あと　まず　何を　しますか。' },
    ],
    options: ['ぎゅうにゅうを　かいます', 'パンを　かいます', 'いえへ　かえります', 'なにも　かいません'],
    note: 'The man says the bread is already at home, so she drops it and buys only the milk. When a second speaker corrects the first, the correction is almost always the answer.',
  },
  {
    ...task(), ...MEET,
    prompt: 'おとこの人は　この　あと　何を　しますか。',
    narration: [
      { speaker: 'narrator', text: 'かいしゃで　おんなの人と　おとこの人が　はなしています。おとこの人は　この　あと　何を　しますか。', pauseAfter: 700 },
      { speaker: 'a', text: 'この　かみを　１０まい　コピーして　ください。', pauseAfter: 300 },
      { speaker: 'b', text: 'はい。その　まえに　でんわを　しても　いいですか。', pauseAfter: 300 },
      { speaker: 'a', text: 'いいですよ。', pauseAfter: 600 },
      { speaker: 'narrator', text: 'おとこの人は　この　あと　何を　しますか。' },
    ],
    options: ['でんわを　します', 'コピーを　します', 'かみを　かいます', 'かいぎに　でます'],
    note: 'その まえに means "before that", so the phone call comes first even though the copying was asked for first. Listen for まえに and あとで — they decide the order.',
  },
  {
    ...task(), ...STATION,
    prompt: 'おんなの人は　どこへ　いきますか。',
    narration: [
      { speaker: 'narrator', text: 'えきで　おんなの人と　えきいんが　はなしています。おんなの人は　どこへ　いきますか。', pauseAfter: 700 },
      { speaker: 'a', text: 'すみません、みなみぐちは　どちらですか。', pauseAfter: 300 },
      { speaker: 'b', text: 'みなみぐちは　いま　こうじ中です。きたぐちを　つかって　ください。', pauseAfter: 300 },
      { speaker: 'a', text: 'わかりました。ありがとうございます。', pauseAfter: 600 },
      { speaker: 'narrator', text: 'おんなの人は　どこへ　いきますか。' },
    ],
    options: ['きたぐち', 'みなみぐち', 'ひがしぐち', 'にしぐち'],
    note: 'She asks for the south exit, but it is under construction, so the staff member sends her to the north exit. The place asked about is rarely the place she goes.',
  },
  {
    ...task(), ...SHOP,
    prompt: 'ふたりは　なんじに　あいますか。',
    narration: [
      { speaker: 'narrator', text: 'ともだち　ふたりが　はなしています。ふたりは　なんじに　あいますか。', pauseAfter: 700 },
      { speaker: 'a', text: 'あした　１０じは　どうですか。', pauseAfter: 300 },
      { speaker: 'b', text: 'すみません、１０じは　じゅぎょうが　あります。１じは　どうですか。', pauseAfter: 300 },
      { speaker: 'a', text: 'いいですよ。じゃあ、１じに。', pauseAfter: 600 },
      { speaker: 'narrator', text: 'ふたりは　なんじに　あいますか。' },
    ],
    options: ['１じ', '１０じ', '１１じ', '２じ'],
    note: 'The first time is rejected because of a class, and the second is agreed. じゃあ signals the final decision.',
  },
  {
    ...task(), ...MEET,
    prompt: 'がくせいは　あした　何を　もって　きますか。',
    narration: [
      { speaker: 'narrator', text: 'がっこうで　せんせいが　はなしています。がくせいは　あした　何を　もって　きますか。', pauseAfter: 700 },
      { speaker: 'a', text: 'あしたは　えを　かきます。えのぐは　がっこうに　ありますから、もって　こなくても　いいです。', pauseAfter: 300 },
      { speaker: 'a', text: 'でも、ふるい　シャツを　わすれないで　ください。', pauseAfter: 600 },
      { speaker: 'narrator', text: 'がくせいは　あした　何を　もって　きますか。' },
    ],
    options: ['ふるい　シャツ', 'えのぐ', 'ノート', 'かさ'],
    note: '～なくてもいいです means you do not need to. The paints are provided; only the old shirt has to be brought.',
  },
  {
    ...task(), ...SHOP,
    prompt: 'おとこの人は　いくら　はらいますか。',
    narration: [
      { speaker: 'narrator', text: 'みせで　おとこの人と　てんいんが　はなしています。おとこの人は　いくら　はらいますか。', pauseAfter: 700 },
      { speaker: 'a', text: 'この　ケーキは　いくらですか。', pauseAfter: 300 },
      { speaker: 'b', text: '１つ　３００えんです。きょうは　２つで　５００えんですよ。', pauseAfter: 300 },
      { speaker: 'a', text: 'じゃあ、２つ　ください。', pauseAfter: 600 },
      { speaker: 'narrator', text: 'おとこの人は　いくら　はらいますか。' },
    ],
    options: ['５００えん', '３００えん', '６００えん', '８００えん'],
    note: 'Two cakes are 500 yen together, not 300 each. Number questions almost always offer the un-discounted total as a distractor.',
  },
  {
    ...task(), ...STATION,
    prompt: 'おんなの人は　なんばんせんへ　いきますか。',
    narration: [
      { speaker: 'narrator', text: 'えきで　おんなの人と　えきいんが　はなしています。おんなの人は　なんばんせんへ　いきますか。', pauseAfter: 700 },
      { speaker: 'a', text: 'とうきょうへ　いきたいです。', pauseAfter: 300 },
      { speaker: 'b', text: 'とうきょうゆきは　３ばんせんです。あ、いまの　でんしゃは　４ばんせんから　でます。', pauseAfter: 300 },
      { speaker: 'a', text: 'じゃあ、４ばんせんですね。', pauseAfter: 600 },
      { speaker: 'narrator', text: 'おんなの人は　なんばんせんへ　いきますか。' },
    ],
    options: ['４ばんせん', '３ばんせん', '１ばんせん', '２ばんせん'],
    note: 'The staff member corrects himself: the usual platform is 3, but this train leaves from 4. あ often introduces the correction that matters.',
  },
  {
    ...task(), ...MEET,
    prompt: 'おんなの人は　だれに　でんわしますか。',
    narration: [
      { speaker: 'narrator', text: 'かいしゃで　ふたりが　はなしています。おんなの人は　だれに　でんわしますか。', pauseAfter: 700 },
      { speaker: 'a', text: 'たなかさんは　きょう　やすみですか。', pauseAfter: 300 },
      { speaker: 'b', text: 'ええ。やまださんが　かわりに　きます。', pauseAfter: 300 },
      { speaker: 'a', text: 'そうですか。じゃあ、やまださんに　でんわします。', pauseAfter: 600 },
      { speaker: 'narrator', text: 'おんなの人は　だれに　でんわしますか。' },
    ],
    options: ['やまださん', 'たなかさん', 'せんせい', 'てんいん'],
    note: 'かわりに means "instead", so Yamada is standing in for Tanaka and is the one to call.',
  },

  /* ---------- ポイント理解 ---------- */
  {
    ...point(), ...WEATHER,
    prompt: 'あしたの　てんきは　どうですか。',
    narration: [
      { speaker: 'narrator', text: 'テレビで　てんきよほうを　きいて　います。あしたの　てんきは　どうですか。', pauseAfter: 700 },
      { speaker: 'a', text: 'きょうは　１日　あめでしたね。あしたの　あさも　あめが　のこりますが、ひるからは　はれるでしょう。', pauseAfter: 600 },
      { speaker: 'narrator', text: 'あしたの　てんきは　どうですか。' },
    ],
    options: ['あさは　あめ、ひるからは　はれ', '１日　あめ', '１日　はれ', 'あさは　はれ、ひるからは　あめ'],
    note: 'きょう and あした are both described. The question asks about tomorrow: rain in the morning, clearing after midday.',
  },
  {
    ...point(), ...MEET,
    prompt: 'おとこの人は　どうして　やすみましたか。',
    narration: [
      { speaker: 'narrator', text: 'かいしゃで　ふたりが　はなしています。おとこの人は　どうして　やすみましたか。', pauseAfter: 700 },
      { speaker: 'a', text: 'きのうは　やすみましたね。かぜですか。', pauseAfter: 300 },
      { speaker: 'b', text: 'いいえ、こどもが　びょうきでした。', pauseAfter: 600 },
      { speaker: 'narrator', text: 'おとこの人は　どうして　やすみましたか。' },
    ],
    options: ['こどもが　びょうきだったから', 'かぜを　ひいたから', 'りょこうに　いったから', 'しごとが　なかったから'],
    note: 'The first guess is denied with いいえ. In ポイント理解 the reason offered first is usually the wrong one.',
  },
  {
    ...point(), ...SHOP,
    prompt: 'おんなの人は　なにを　さがして　いますか。',
    narration: [
      { speaker: 'narrator', text: 'みせで　おんなの人と　てんいんが　はなしています。おんなの人は　なにを　さがして　いますか。', pauseAfter: 700 },
      { speaker: 'a', text: 'すみません、くろい　かばんは　ありますか。', pauseAfter: 300 },
      { speaker: 'b', text: 'かばんは　２かいです。くつは　３かいですよ。', pauseAfter: 300 },
      { speaker: 'a', text: 'ありがとうございます。２かいへ　いきます。', pauseAfter: 600 },
      { speaker: 'narrator', text: 'おんなの人は　なにを　さがして　いますか。' },
    ],
    options: ['かばん', 'くつ', 'ぼうし', 'ふく'],
    note: 'Shoes are mentioned but only as extra information. She asked for a bag and goes to the bag floor.',
  },
  {
    ...point(), ...STATION,
    prompt: 'でんしゃは　なんぷん　おくれて　いますか。',
    narration: [
      { speaker: 'narrator', text: 'えきで　あんないを　きいて　います。でんしゃは　なんぷん　おくれて　いますか。', pauseAfter: 700 },
      { speaker: 'a', text: 'おきゃくさまに　おしらせします。あめの　ため、でんしゃは　１０ぷん　おくれて　います。', pauseAfter: 300 },
      { speaker: 'a', text: 'つぎの　でんしゃは　９じ２０ぷんに　まいります。', pauseAfter: 600 },
      { speaker: 'narrator', text: 'でんしゃは　なんぷん　おくれて　いますか。' },
    ],
    options: ['１０ぷん', '２０ぷん', '９ふん', '３０ぷん'],
    note: 'Two numbers are read out: the delay (10 minutes) and the arrival time (9:20). The question asks for the delay.',
  },
  {
    ...point(), ...MEET,
    prompt: 'パーティーは　どこで　しますか。',
    narration: [
      { speaker: 'narrator', text: 'ともだちが　はなしています。パーティーは　どこで　しますか。', pauseAfter: 700 },
      { speaker: 'a', text: 'パーティーは　こうえんで　しませんか。', pauseAfter: 300 },
      { speaker: 'b', text: 'あめが　ふるかも　しれません。わたしの　いえは　どうですか。', pauseAfter: 300 },
      { speaker: 'a', text: 'いいですね。そう　しましょう。', pauseAfter: 600 },
      { speaker: 'narrator', text: 'パーティーは　どこで　しますか。' },
    ],
    options: ['おんなの人の　いえ', 'こうえん', 'がっこう', 'レストラン'],
    note: 'そうしましょう accepts the second suggestion. The park was only proposed, never agreed.',
  },
  {
    ...point(), ...SHOP,
    prompt: 'おとこの人は　いつ　りょこうに　いきますか。',
    narration: [
      { speaker: 'narrator', text: 'ふたりが　はなしています。おとこの人は　いつ　りょこうに　いきますか。', pauseAfter: 700 },
      { speaker: 'a', text: 'なつやすみに　りょこうに　いきますか。', pauseAfter: 300 },
      { speaker: 'b', text: 'なつは　しごとが　いそがしいです。あきに　いきます。', pauseAfter: 600 },
      { speaker: 'narrator', text: 'おとこの人は　いつ　りょこうに　いきますか。' },
    ],
    options: ['あき', 'なつ', 'ふゆ', 'はる'],
    note: 'Summer is ruled out because work is busy. The season he names afterwards is the answer.',
  },
  {
    ...point(), ...MEET,
    prompt: 'おんなの人は　なにを　わすれましたか。',
    narration: [
      { speaker: 'narrator', text: 'ふたりが　はなしています。おんなの人は　なにを　わすれましたか。', pauseAfter: 700 },
      { speaker: 'a', text: 'あっ、かさを　わすれました。', pauseAfter: 300 },
      { speaker: 'b', text: 'かさは　ここに　ありますよ。', pauseAfter: 300 },
      { speaker: 'a', text: 'ほんとうだ。じゃあ、さいふが　ありません。', pauseAfter: 600 },
      { speaker: 'narrator', text: 'おんなの人は　なにを　わすれましたか。' },
    ],
    options: ['さいふ', 'かさ', 'かばん', 'ほん'],
    note: 'The umbrella turns out to be there. What is actually missing is the wallet, named at the end.',
  },
  {
    ...point(), ...WEATHER,
    prompt: 'あしたは　なにを　もって　いきますか。',
    narration: [
      { speaker: 'narrator', text: 'てんきよほうを　きいて　います。あしたは　なにを　もって　いきますか。', pauseAfter: 700 },
      { speaker: 'a', text: 'あしたは　あめは　ふりません。でも、かぜが　つよいです。ぼうしは　とばされますから、きを　つけて　ください。', pauseAfter: 600 },
      { speaker: 'narrator', text: 'あしたは　なにを　もって　いきますか。' },
    ],
    options: ['なにも　いりません', 'かさ', 'ぼうし', 'コート'],
    note: 'It will not rain, so no umbrella; hats are said to blow away, so not a hat either. Nothing is needed.',
  },

  /* ---------- 発話表現 ---------- */
  {
    ...speech(), ...SHOP,
    prompt: 'この　ばめんで　何と　いいますか。',
    narration: [{ speaker: 'narrator', text: 'みせで　ねだんが　わかりません。てんいんに　ききます。何と　いいますか。' }],
    options: ['すみません、いくらですか。', 'すみません、たかいですか。', 'すみません、かいましたか。', 'すみません、うりますか。'],
    note: 'いくらですか is the set way to ask a price.',
  },
  {
    ...speech(), ...SHOP,
    prompt: 'この　ばめんで　何と　いいますか。',
    narration: [{ speaker: 'narrator', text: 'みせで　ふくろが　ほしいです。てんいんに　何と　いいますか。' }],
    options: ['ふくろを　ください。', 'ふくろが　あります。', 'ふくろを　あげます。', 'ふくろでしょう。'],
    note: '～をください is how you ask to be given something.',
  },
  {
    ...speech(), ...STATION,
    prompt: 'この　ばめんで　何と　いいますか。',
    narration: [{ speaker: 'narrator', text: 'えきへの　みちが　わかりません。しらない人に　何と　いいますか。' }],
    options: ['すみません、えきは　どこですか。', 'すみません、えきへ　いきました。', 'すみません、えきが　すきです。', 'すみません、えきは　とおいです。'],
    note: 'どこですか asks for a location; the other three state things instead of asking.',
  },
  {
    ...speech(), ...STATION,
    prompt: 'この　ばめんで　何と　いいますか。',
    narration: [{ speaker: 'narrator', text: 'でんしゃの　中で　人の　あしを　ふみました。何と　いいますか。' }],
    options: ['すみません。', 'ありがとう。', 'おねがいします。', 'いらっしゃいませ。'],
    note: 'すみません is the apology when you have caused someone trouble.',
  },
  {
    ...speech(), ...MEET,
    prompt: 'この　ばめんで　何と　いいますか。',
    narration: [{ speaker: 'narrator', text: 'あさ、かいしゃで　せんせいに　あいました。何と　いいますか。' }],
    options: ['おはようございます。', 'おやすみなさい。', 'いってきます。', 'ごちそうさま。'],
    note: 'おはようございます is the morning greeting; おやすみなさい is said at night.',
  },
  {
    ...speech(), ...MEET,
    prompt: 'この　ばめんで　何と　いいますか。',
    narration: [{ speaker: 'narrator', text: 'ともだちに　ペンを　かりたいです。何と　いいますか。' }],
    options: ['ペンを　かして　ください。', 'ペンを　かりて　ください。', 'ペンを　かえして　ください。', 'ペンを　かって　ください。'],
    note: 'かす is to lend and かりる is to borrow. Asking the other person to act means かして ください.',
  },
  {
    ...speech(), ...MEET,
    prompt: 'この　ばめんで　何と　いいますか。',
    narration: [{ speaker: 'narrator', text: 'さきに　かえります。まだ　しごとを　して　いる　人に　何と　いいますか。' }],
    options: ['おさきに　しつれいします。', 'いってらっしゃい。', 'ただいま。', 'はじめまして。'],
    note: 'おさきに しつれいします is what you say when leaving before others.',
  },
  {
    ...speech(), ...SHOP,
    prompt: 'この　ばめんで　何と　いいますか。',
    narration: [{ speaker: 'narrator', text: 'レストランで　りょうりを　たべおわりました。何と　いいますか。' }],
    options: ['ごちそうさまでした。', 'いただきます。', 'おかえりなさい。', 'おめでとうございます。'],
    note: 'いただきます opens a meal and ごちそうさまでした closes it.',
  },

  /* ---------- 即時応答 ---------- */
  { ...quick(), ...MEET, prompt: 'きいて、いちばん　いい　へんじを　えらんで　ください。',
    narration: [{ speaker: 'a', text: 'この　ペン、つかっても　いいですか。' }],
    options: ['ええ、どうぞ。', 'ええ、つかいました。', 'いいえ、ペンです。', 'はい、かいました。'],
    note: '～てもいいですか asks permission, and どうぞ grants it.' },
  { ...quick(), ...MEET, prompt: 'きいて、いちばん　いい　へんじを　えらんで　ください。',
    narration: [{ speaker: 'a', text: 'しゅくだいは　もう　おわりましたか。' }],
    options: ['いいえ、まだです。', 'いいえ、おわります。', 'はい、まだです。', 'はい、しません。'],
    note: 'もう asks whether something is done already; まだです answers "not yet".' },
  { ...quick(), ...SHOP, prompt: 'きいて、いちばん　いい　へんじを　えらんで　ください。',
    narration: [{ speaker: 'a', text: 'いっしょに　ひるごはんを　たべませんか。' }],
    options: ['いいですね、いきましょう。', 'はい、たべました。', 'いいえ、ひるごはんです。', 'ええ、たべて　います。'],
    note: '～ませんか is an invitation; you accept it with a suggestion, not a report.' },
  { ...quick(), ...STATION, prompt: 'きいて、いちばん　いい　へんじを　えらんで　ください。',
    narration: [{ speaker: 'a', text: 'その　にもつ、おもいでしょう。もちましょうか。' }],
    options: ['ありがとうございます。おねがいします。', 'はい、おもいです。', 'いいえ、もちません。', 'にもつが　あります。'],
    note: '～ましょうか offers help, so the reply accepts or declines the offer.' },
  { ...quick(), ...MEET, prompt: 'きいて、いちばん　いい　へんじを　えらんで　ください。',
    narration: [{ speaker: 'a', text: 'すみません、いま　なんじですか。' }],
    options: ['３じ１５ふんです。', '３じかんです。', 'げつようびです。', 'ここです。'],
    note: 'なんじ asks a clock time; ３じかん would be a duration.' },
  { ...quick(), ...SHOP, prompt: 'きいて、いちばん　いい　へんじを　えらんで　ください。',
    narration: [{ speaker: 'a', text: 'この　ケーキ、おいしいですね。' }],
    options: ['ええ、ほんとうに。', 'ええ、たべません。', 'いいえ、ケーキです。', 'はい、つくりましょう。'],
    note: 'A ～ですね comment invites agreement.' },
  { ...quick(), ...MEET, prompt: 'きいて、いちばん　いい　へんじを　えらんで　ください。',
    narration: [{ speaker: 'a', text: 'たなかさんは　どこですか。' }],
    options: ['かいぎしつに　います。', 'かいぎしつに　あります。', '３じに　います。', 'たなかさんです。'],
    note: 'People take います, not あります.' },
  { ...quick(), ...STATION, prompt: 'きいて、いちばん　いい　へんじを　えらんで　ください。',
    narration: [{ speaker: 'a', text: 'つぎの　でんしゃは　なんじに　きますか。' }],
    options: ['８じ４０ぷんです。', '８ばんせんです。', 'とうきょうです。', 'でんしゃです。'],
    note: 'なんじ asks for a time, not a platform or a destination.' },
  { ...quick(), ...MEET, prompt: 'きいて、いちばん　いい　へんじを　えらんで　ください。',
    narration: [{ speaker: 'a', text: 'あした、いっしょに　いきましょう。' }],
    options: ['はい、そう　しましょう。', 'はい、いきました。', 'いいえ、あしたです。', 'ええ、いって　います。'],
    note: '～ましょう proposes doing something together; そうしましょう agrees.' },
  { ...quick(), ...SHOP, prompt: 'きいて、いちばん　いい　へんじを　えらんで　ください。',
    narration: [{ speaker: 'a', text: 'おつりです。ありがとうございました。' }],
    options: ['どうも。', 'どういたしまして。', 'すみませんでした。', 'いってらっしゃい。'],
    note: 'A customer answers a shop’s thanks lightly with どうも; どういたしまして answers being thanked for a favour.' },
  { ...quick(), ...MEET, prompt: 'きいて、いちばん　いい　へんじを　えらんで　ください。',
    narration: [{ speaker: 'a', text: 'かぜですか。だいじょうぶですか。' }],
    options: ['ええ、すこし　あたまが　いたいです。', 'ええ、かぜが　つよいです。', 'いいえ、だいじょうぶでした。', 'はい、かぜを　ふきます。'],
    note: 'かぜ here is a cold, not wind — the reply has to be about health.' },
  { ...quick(), ...MEET, prompt: 'きいて、いちばん　いい　へんじを　えらんで　ください。',
    narration: [{ speaker: 'a', text: 'にほんごが　じょうずですね。' }],
    options: ['いいえ、まだまだです。', 'はい、じょうずです。', 'いいえ、にほんごです。', 'はい、へたです。'],
    note: 'A compliment is politely deflected with いいえ、まだまだです rather than accepted outright.' },
];


const n4: Script[] = [
  /* ---------- 課題理解 ---------- */
  {
    ...task(), ...MEET,
    prompt: '女の人は　このあと　まず　何を　しますか。',
    narration: [
      { speaker: 'narrator', text: '会社で　男の人と　女の人が　話しています。女の人は　このあと　まず　何を　しますか。', pauseAfter: 700 },
      { speaker: 'a', text: '会議の　資料、印刷して　おいて　くれますか。', pauseAfter: 300 },
      { speaker: 'b', text: 'はい。あ、その前に　部長に　確認した　ほうが　いいですよね。', pauseAfter: 300 },
      { speaker: 'a', text: 'そうですね。じゃあ　お願いします。', pauseAfter: 600 },
      { speaker: 'narrator', text: '女の人は　このあと　まず　何を　しますか。' },
    ],
    options: ['部長に　確認します', '資料を　印刷します', '会議に　出ます', '部長に　電話します'],
    note: 'その前に reorders the two tasks: checking with the manager comes before printing.',
  },
  {
    ...task(), ...SHOP,
    prompt: '男の人は　何を　買いますか。',
    narration: [
      { speaker: 'narrator', text: '店で　男の人と　店員が　話しています。男の人は　何を　買いますか。', pauseAfter: 700 },
      { speaker: 'a', text: 'この　青い　シャツの　Ｍサイズは　ありますか。', pauseAfter: 300 },
      { speaker: 'b', text: '青は　Ｌしか　残って　いません。白なら　Ｍが　ございます。', pauseAfter: 300 },
      { speaker: 'a', text: 'サイズが　大事なので、そちらに　します。', pauseAfter: 600 },
      { speaker: 'narrator', text: '男の人は　何を　買いますか。' },
    ],
    options: ['白い　シャツの　Ｍサイズ', '青い　シャツの　Ｌサイズ', '青い　シャツの　Ｍサイズ', '白い　シャツの　Ｌサイズ'],
    note: 'He says size matters more than colour, so そちら points at the white M.',
  },
  {
    ...task(), ...STATION,
    prompt: '女の人は　どう　やって　行きますか。',
    narration: [
      { speaker: 'narrator', text: '駅で　女の人と　駅員が　話しています。女の人は　どう　やって　行きますか。', pauseAfter: 700 },
      { speaker: 'a', text: '空港まで　行きたいんですが。', pauseAfter: 300 },
      { speaker: 'b', text: '電車が　早いですが、今日は　工事で　止まって　います。バスなら　１時間ほどです。', pauseAfter: 300 },
      { speaker: 'a', text: '急いで　いるので、それで　行きます。', pauseAfter: 600 },
      { speaker: 'narrator', text: '女の人は　どう　やって　行きますか。' },
    ],
    options: ['バス', '電車', 'タクシー', '歩いて'],
    note: 'The train is faster in principle but stopped today, so それ refers to the bus.',
  },
  {
    ...task(), ...MEET,
    prompt: '男の人は　いつまでに　出しますか。',
    narration: [
      { speaker: 'narrator', text: '大学で　先生と　学生が　話しています。男の人は　いつまでに　出しますか。', pauseAfter: 700 },
      { speaker: 'a', text: 'レポートの　締め切りは　金曜日ですね。', pauseAfter: 300 },
      { speaker: 'b', text: 'ええ。でも　金曜は　休みなので、木曜の　夕方までに　出して　ください。', pauseAfter: 300 },
      { speaker: 'a', text: 'わかりました。', pauseAfter: 600 },
      { speaker: 'narrator', text: '男の人は　いつまでに　出しますか。' },
    ],
    options: ['木曜日の　夕方', '金曜日の　夕方', '木曜日の　朝', '土曜日の　朝'],
    note: 'The stated deadline is Friday, but the office is closed, so the real deadline moves to Thursday evening.',
  },
  {
    ...task(), ...SHOP,
    prompt: '二人は　何を　持って　行きますか。',
    narration: [
      { speaker: 'narrator', text: '友だち二人が　話しています。二人は　何を　持って　行きますか。', pauseAfter: 700 },
      { speaker: 'a', text: '花見だから、飲み物と　お弁当を　用意しようか。', pauseAfter: 300 },
      { speaker: 'b', text: 'お弁当は　私が　作るよ。飲み物は　公園でも　買えるから　いらないね。', pauseAfter: 300 },
      { speaker: 'a', text: 'じゃあ、レジャーシートだけ　持って　いくね。', pauseAfter: 600 },
      { speaker: 'narrator', text: '男の人は　何を　持って　行きますか。' },
    ],
    options: ['レジャーシート', 'お弁当', '飲み物', '何も　持って　行きません'],
    note: 'She makes the food, drinks can be bought there, so his job is the mat only.',
  },
  {
    ...task(), ...MEET,
    prompt: '女の人は　これから　どこへ　行きますか。',
    narration: [
      { speaker: 'narrator', text: '会社で　二人が　話しています。女の人は　これから　どこへ　行きますか。', pauseAfter: 700 },
      { speaker: 'a', text: '銀行に　行って　きます。', pauseAfter: 300 },
      { speaker: 'b', text: '銀行なら　もう　閉まって　いますよ。三時までですから。', pauseAfter: 300 },
      { speaker: 'a', text: 'あ、そうですね。じゃあ　郵便局に　寄ります。', pauseAfter: 600 },
      { speaker: 'narrator', text: '女の人は　これから　どこへ　行きますか。' },
    ],
    options: ['郵便局', '銀行', '会社', '駅'],
    note: 'The bank is already closed, so she changes her plan to the post office.',
  },
  {
    ...task(), ...WEATHER,
    prompt: '運動会は　いつ　しますか。',
    narration: [
      { speaker: 'narrator', text: '学校で　先生が　話して　います。運動会は　いつ　しますか。', pauseAfter: 700 },
      { speaker: 'a', text: '日曜日の　運動会ですが、天気予報に　よると　その日は　雨だそうです。', pauseAfter: 300 },
      { speaker: 'a', text: '土曜日は　晴れる　予定ですので、一日　早めて　行います。', pauseAfter: 600 },
      { speaker: 'narrator', text: '運動会は　いつ　しますか。' },
    ],
    options: ['土曜日', '日曜日', '月曜日', '来週の　日曜日'],
    note: '一日早めて means moved one day earlier, so Sunday becomes Saturday.',
  },
  {
    ...task(), ...STATION,
    prompt: '男の人は　まず　何を　しますか。',
    narration: [
      { speaker: 'narrator', text: '駅で　男の人と　駅員が　話しています。男の人は　まず　何を　しますか。', pauseAfter: 700 },
      { speaker: 'a', text: 'かばんを　電車の　中に　忘れて　しまいました。', pauseAfter: 300 },
      { speaker: 'b', text: 'それでは　こちらの　用紙に　特徴を　書いて　ください。見つかったら　お電話します。', pauseAfter: 300 },
      { speaker: 'a', text: 'わかりました。', pauseAfter: 600 },
      { speaker: 'narrator', text: '男の人は　まず　何を　しますか。' },
    ],
    options: ['用紙に　書きます', '電話を　待ちます', '電車に　乗ります', 'かばんを　買います'],
    note: 'The phone call comes later, if the bag turns up. His task now is filling in the form.',
  },

  /* ---------- ポイント理解 ---------- */
  {
    ...point(), ...MEET,
    prompt: '女の人は　どうして　引っ越しましたか。',
    narration: [
      { speaker: 'narrator', text: '二人が　話しています。女の人は　どうして　引っ越しましたか。', pauseAfter: 700 },
      { speaker: 'a', text: '新しい　部屋、駅から　近くて　いいですね。', pauseAfter: 300 },
      { speaker: 'b', text: 'ええ。でも　選んだ　理由は　それでは　なくて、前の　部屋は　隣の　音が　うるさかったんです。', pauseAfter: 600 },
      { speaker: 'narrator', text: '女の人は　どうして　引っ越しましたか。' },
    ],
    options: ['前の　部屋が　うるさかったから', '駅から　近いから', '部屋が　狭かったから', '家賃が　高かったから'],
    note: 'それではなくて explicitly rejects the convenient location as the reason.',
  },
  {
    ...point(), ...SHOP,
    prompt: '男の人は　全部で　いくら　払いますか。',
    narration: [
      { speaker: 'narrator', text: '店で　男の人と　店員が　話しています。男の人は　全部で　いくら　払いますか。', pauseAfter: 700 },
      { speaker: 'a', text: '本が　１２００円、ノートが　３００円ですね。', pauseAfter: 300 },
      { speaker: 'b', text: 'はい。会員カードを　お持ちでしたら　２００円　引きます。', pauseAfter: 300 },
      { speaker: 'a', text: 'あります。これです。', pauseAfter: 600 },
      { speaker: 'narrator', text: '男の人は　全部で　いくら　払いますか。' },
    ],
    options: ['１３００円', '１５００円', '１２００円', '１１００円'],
    note: '1200 + 300 = 1500, minus the 200 discount he qualifies for.',
  },
  {
    ...point(), ...WEATHER,
    prompt: '今週末の　天気は　どう　なりますか。',
    narration: [
      { speaker: 'narrator', text: '天気予報を　聞いて　います。今週末の　天気は　どう　なりますか。', pauseAfter: 700 },
      { speaker: 'a', text: '今週は　晴れの　日が　続いて　いますが、週末は　変わります。', pauseAfter: 300 },
      { speaker: 'a', text: '土曜日は　くもり、日曜日は　朝から　雨が　降るでしょう。', pauseAfter: 600 },
      { speaker: 'narrator', text: '今週末の　天気は　どう　なりますか。' },
    ],
    options: ['土曜は　くもり、日曜は　雨', '土曜も　日曜も　晴れ', '土曜は　雨、日曜は　くもり', '週末は　ずっと　晴れ'],
    note: 'The sunny run describes this week, not the weekend. Hold on to which period the question asks about.',
  },
  {
    ...point(), ...MEET,
    prompt: '男の人は　何が　心配ですか。',
    narration: [
      { speaker: 'narrator', text: '会社で　二人が　話しています。男の人は　何が　心配ですか。', pauseAfter: 700 },
      { speaker: 'a', text: '新しい　計画、予算は　足りそうですか。', pauseAfter: 300 },
      { speaker: 'b', text: '予算は　問題ありません。ただ、人が　足りないんです。', pauseAfter: 600 },
      { speaker: 'narrator', text: '男の人は　何が　心配ですか。' },
    ],
    options: ['人が　足りない　こと', '予算が　足りない　こと', '時間が　ない　こと', '場所が　ない　こと'],
    note: 'ただ introduces the real problem after dismissing the budget.',
  },
  {
    ...point(), ...STATION,
    prompt: '電車は　何時に　出発しますか。',
    narration: [
      { speaker: 'narrator', text: '駅の　アナウンスを　聞いて　います。電車は　何時に　出発しますか。', pauseAfter: 700 },
      { speaker: 'a', text: '１０時発の　電車は、事故の　影響で　２０分　遅れて　出発いたします。', pauseAfter: 300 },
      { speaker: 'a', text: 'お急ぎの　お客様は　１０時１５分発の　各駅停車を　ご利用ください。', pauseAfter: 600 },
      { speaker: 'narrator', text: 'はじめの　電車は　何時に　出発しますか。' },
    ],
    options: ['１０時２０分', '１０時', '１０時１５分', '１０時３０分'],
    note: '10:00 delayed by 20 minutes is 10:20. The 10:15 local is a different train.',
  },
  {
    ...point(), ...SHOP,
    prompt: '女の人は　何が　気に入りませんでしたか。',
    narration: [
      { speaker: 'narrator', text: '店で　二人が　話しています。女の人は　何が　気に入りませんでしたか。', pauseAfter: 700 },
      { speaker: 'a', text: 'この　テーブル、デザインが　すてきですね。', pauseAfter: 300 },
      { speaker: 'b', text: 'ええ、色も　好きです。でも　うちの　部屋には　大きすぎます。', pauseAfter: 600 },
      { speaker: 'narrator', text: '女の人は　何が　気に入りませんでしたか。' },
    ],
    options: ['大きさ', 'デザイン', '色', '値段'],
    note: 'She praises the design and colour; でも introduces the one thing that does not work.',
  },
  {
    ...point(), ...MEET,
    prompt: '会議は　どこで　行いますか。',
    narration: [
      { speaker: 'narrator', text: '会社で　二人が　話しています。会議は　どこで　行いますか。', pauseAfter: 700 },
      { speaker: 'a', text: '会議は　いつもの　三階の　部屋ですか。', pauseAfter: 300 },
      { speaker: 'b', text: '今日は　人数が　多いので、一階の　大きい　部屋を　使います。', pauseAfter: 600 },
      { speaker: 'narrator', text: '会議は　どこで　行いますか。' },
    ],
    options: ['一階の　部屋', '三階の　部屋', '二階の　部屋', '四階の　部屋'],
    note: 'The usual room is named first as the trap; the change is given as the answer.',
  },
  {
    ...point(), ...MEET,
    prompt: '女の人は　週に　何回　通って　いますか。',
    narration: [
      { speaker: 'narrator', text: '二人が　話しています。女の人は　週に　何回　通って　いますか。', pauseAfter: 700 },
      { speaker: 'a', text: '毎日　ジムに　行って　いるんですか。', pauseAfter: 300 },
      { speaker: 'b', text: 'いいえ、そんなに　行けません。月曜と　木曜だけです。', pauseAfter: 600 },
      { speaker: 'narrator', text: '女の人は　週に　何回　通って　いますか。' },
    ],
    options: ['２回', '毎日', '３回', '１回'],
    note: 'She names two days, so the count is two — the question asks how many times, not which days.',
  },

  /* ---------- 発話表現 ---------- */
  { ...speech(), ...MEET, prompt: 'この　場面で　何と　言いますか。',
    narration: [{ speaker: 'narrator', text: '会議に　少し　遅れて　入ります。何と　言いますか。' }],
    options: ['遅れて　すみません。', '遅れて　いますか。', '遅れても　いいですか。', '遅れて　ください。'],
    note: 'An apology for your own lateness uses the て-form plus すみません.' },
  { ...speech(), ...MEET, prompt: 'この　場面で　何と　言いますか。',
    narration: [{ speaker: 'narrator', text: '重そうな　荷物を　持って　いる　人を　手伝いたいです。何と　言いますか。' }],
    options: ['お持ちしましょうか。', '持って　ください。', '持っても　いいですか。', '持ちたいですか。'],
    note: 'お + stem + しましょうか is the humble way to offer help.' },
  { ...speech(), ...SHOP, prompt: 'この　場面で　何と　言いますか。',
    narration: [{ speaker: 'narrator', text: '店で　買った　服の　サイズが　合いませんでした。取りかえて　ほしいです。何と　言いますか。' }],
    options: ['サイズを　取りかえて　いただけませんか。', 'サイズを　取りかえましょうか。', 'サイズが　合いましたね。', 'サイズを　取りかえて　あげます。'],
    note: '～ていただけませんか is the polite way to ask someone to do something for you.' },
  { ...speech(), ...STATION, prompt: 'この　場面で　何と　言いますか。',
    narration: [{ speaker: 'narrator', text: '電車の　中で　席を　ゆずりたいです。お年寄りに　何と　言いますか。' }],
    options: ['どうぞ、お座り　ください。', 'どうぞ、座りましょうか。', '座っても　いいですか。', 'ここに　座りたいです。'],
    note: 'お + stem + ください is the honorific invitation to do something.' },
  { ...speech(), ...MEET, prompt: 'この　場面で　何と　言いますか。',
    narration: [{ speaker: 'narrator', text: '先生の　説明が　よく　聞こえませんでした。何と　言いますか。' }],
    options: ['すみません、もう一度　お願いします。', 'すみません、もう一度　言いました。', 'すみません、聞こえましたか。', 'すみません、説明しましょうか。'],
    note: 'もう一度お願いします politely asks for a repeat.' },
  { ...speech(), ...MEET, prompt: 'この　場面で　何と　言いますか。',
    narration: [{ speaker: 'narrator', text: '友だちが　試験に　合格しました。何と　言いますか。' }],
    options: ['おめでとう。よかったね。', 'ありがとう。よかったね。', 'ざんねんだったね。', 'お大事に。'],
    note: 'おめでとう congratulates; お大事に is for someone who is unwell.' },
  { ...speech(), ...SHOP, prompt: 'この　場面で　何と　言いますか。',
    narration: [{ speaker: 'narrator', text: '店で　商品を　手に　取って　見たいです。店員に　何と　言いますか。' }],
    options: ['見せて　いただけますか。', '見せて　あげますか。', '見ても　いましたか。', '見せましょうか。'],
    note: '～ていただけますか asks the other person to do something for you.' },
  { ...speech(), ...MEET, prompt: 'この　場面で　何と　言いますか。',
    narration: [{ speaker: 'narrator', text: '友だちの　誘いを　断りたいです。何と　言いますか。' }],
    options: ['せっかくですが、今日は　ちょっと…。', 'せっかくですが、行きましょう。', 'ぜひ　行きたく　ありません。', '行っても　いいですか。'],
    note: 'Japanese refusals trail off; ちょっと… declines without a blunt no.' },

  /* ---------- 即時応答 ---------- */
  { ...quick(), ...MEET, prompt: '聞いて、最も　よい　返事を　選んで　ください。',
    narration: [{ speaker: 'a', text: 'この　書類、明日までに　お願いできますか。' }],
    options: ['はい、承知しました。', 'はい、お願いしました。', 'いいえ、書類です。', 'ええ、明日でした。'],
    note: 'お願いできますか is a request; 承知しました accepts it.' },
  { ...quick(), ...MEET, prompt: '聞いて、最も　よい　返事を　選んで　ください。',
    narration: [{ speaker: 'a', text: 'コーヒーでも　いかがですか。' }],
    options: ['ありがとうございます。いただきます。', 'ありがとうございます。あげます。', 'いいえ、コーヒーです。', 'はい、飲みました。'],
    note: 'いかがですか offers; いただきます accepts politely.' },
  { ...quick(), ...STATION, prompt: '聞いて、最も　よい　返事を　選んで　ください。',
    narration: [{ speaker: 'a', text: 'この　電車、新宿に　止まりますか。' }],
    options: ['いいえ、次の　電車です。', 'いいえ、新宿です。', 'はい、止まりました。', 'ええ、乗りましょう。'],
    note: 'The reply has to answer whether this train stops there, and redirect if not.' },
  { ...quick(), ...MEET, prompt: '聞いて、最も　よい　返事を　選んで　ください。',
    narration: [{ speaker: 'a', text: '会議の　時間、変わったって　聞きましたけど。' }],
    options: ['ええ、三時からに　なりました。', 'ええ、変わりましょう。', 'いいえ、聞きました。', 'はい、会議です。'],
    note: 'The speaker is confirming a rumour, so the reply supplies the detail.' },
  { ...quick(), ...SHOP, prompt: '聞いて、最も　よい　返事を　選んで　ください。',
    narration: [{ speaker: 'a', text: 'お支払いは　カードで　よろしいですか。' }],
    options: ['はい、これで　お願いします。', 'はい、カードが　あります。', 'いいえ、支払いました。', 'ええ、よろしいです。'],
    note: 'よろしいですか confirms a choice; you hand over the card as you accept.' },
  { ...quick(), ...MEET, prompt: '聞いて、最も　よい　返事を　選んで　ください。',
    narration: [{ speaker: 'a', text: '手伝いましょうか。' }],
    options: ['すみません、助かります。', 'すみません、手伝いました。', 'いいえ、手伝いましょう。', 'はい、手伝って　います。'],
    note: '助かります is the natural way to accept an offer of help.' },
  { ...quick(), ...MEET, prompt: '聞いて、最も　よい　返事を　選んで　ください。',
    narration: [{ speaker: 'a', text: '明日の　パーティー、来られますか。' }],
    options: ['すみません、ちょっと　用事が　あって。', 'すみません、来ました。', 'はい、来られました。', 'ええ、パーティーです。'],
    note: 'A soft refusal gives a reason and trails off rather than saying いいえ.' },
  { ...quick(), ...STATION, prompt: '聞いて、最も　よい　返事を　選んで　ください。',
    narration: [{ speaker: 'a', text: '切符を　なくして　しまったんですが。' }],
    options: ['それでは　こちらで　手続きを　お願いします。', 'それでは　切符を　どうぞ。', 'はい、なくしました。', 'いいえ、切符です。'],
    note: 'The speaker reports a problem, so the reply offers a next step.' },
  { ...quick(), ...MEET, prompt: '聞いて、最も　よい　返事を　選んで　ください。',
    narration: [{ speaker: 'a', text: 'この　資料、もう　読みましたか。' }],
    options: ['いいえ、まだ　読んで　いません。', 'いいえ、読みました。', 'はい、まだです。', 'ええ、読みましょう。'],
    note: 'もう…か is answered with either はい、読みました or いいえ、まだ読んでいません.' },
  { ...quick(), ...SHOP, prompt: '聞いて、最も　よい　返事を　選んで　ください。',
    narration: [{ speaker: 'a', text: '袋は　ご利用に　なりますか。' }],
    options: ['いえ、けっこうです。', 'いえ、利用しました。', 'はい、袋です。', 'ええ、ご利用ください。'],
    note: 'けっこうです politely declines. ご利用ください would be telling the clerk what to do.' },
  { ...quick(), ...MEET, prompt: '聞いて、最も　よい　返事を　選んで　ください。',
    narration: [{ speaker: 'a', text: '風邪、まだ　治らないんですか。' }],
    options: ['ええ、なかなか　よく　ならなくて。', 'ええ、治りました。', 'いいえ、風邪です。', 'はい、治りましょう。'],
    note: 'なかなか + negative expresses that something is not improving as hoped.' },
  { ...quick(), ...MEET, prompt: '聞いて、最も　よい　返事を　選んで　ください。',
    narration: [{ speaker: 'a', text: 'お先に　失礼します。' }],
    options: ['お疲れさまでした。', 'いってらっしゃい。', 'おかえりなさい。', 'はじめまして。'],
    note: 'お疲れさまでした is the fixed reply when a colleague leaves for the day.' },
];


const n3: Script[] = [
  /* ---------- 課題理解 ---------- */
  {
    ...task(), ...MEET,
    prompt: '男の人は　このあと　まず　何を　しますか。',
    narration: [
      { speaker: 'narrator', text: '会社で　女の人と　男の人が　話しています。男の人は　このあと　まず　何を　しますか。', pauseAfter: 700 },
      { speaker: 'a', text: '来週の　説明会、参加者リストは　できましたか。', pauseAfter: 300 },
      { speaker: 'b', text: 'はい。会場の　予約も　済みました。', pauseAfter: 300 },
      { speaker: 'a', text: 'では　案内メールを。あ、その前に　部長に　人数を　報告しておいて。', pauseAfter: 600 },
      { speaker: 'narrator', text: '男の人は　このあと　まず　何を　しますか。' },
    ],
    options: ['部長に　人数を　報告する', '案内メールを　送る', '会場を　予約する', '参加者リストを　作る'],
    note: 'Two tasks are already done. Of the two remaining, その前に puts the report ahead of the email.',
  },
  {
    ...task(), ...SHOP,
    prompt: '女の人は　どの　プランに　しますか。',
    narration: [
      { speaker: 'narrator', text: '旅行会社で　女の人と　店員が　話しています。女の人は　どの　プランに　しますか。', pauseAfter: 700 },
      { speaker: 'a', text: '三泊四日で　できるだけ　安い　ものが　いいんですが。', pauseAfter: 300 },
      { speaker: 'b', text: '一番　安いのは　こちらですが、朝食が　付いて　いません。', pauseAfter: 300 },
      { speaker: 'a', text: '朝は　しっかり　食べたいので、その　次の　ものに　します。', pauseAfter: 600 },
      { speaker: 'narrator', text: '女の人は　どの　プランに　しますか。' },
    ],
    options: ['二番目に　安い　プラン', '一番　安い　プラン', '一番　高い　プラン', '朝食なしの　プラン'],
    note: 'She wants cheap but insists on breakfast, so she moves one step up from the cheapest.',
  },
  {
    ...task(), ...STATION,
    prompt: '男の人は　何番の　バスに　乗りますか。',
    narration: [
      { speaker: 'narrator', text: 'バス乗り場で　男の人と　係員が　話しています。男の人は　何番の　バスに　乗りますか。', pauseAfter: 700 },
      { speaker: 'a', text: '美術館へ　行きたいんですが。', pauseAfter: 300 },
      { speaker: 'b', text: '五番と　七番、どちらも　行きますよ。五番は　各停で　三十分、七番は　直行で　十五分です。', pauseAfter: 300 },
      { speaker: 'a', text: '待ち合わせが　あるので、早いほうで　お願いします。', pauseAfter: 600 },
      { speaker: 'narrator', text: '男の人は　何番の　バスに　乗りますか。' },
    ],
    options: ['七番', '五番', '三番', '十五番'],
    note: 'Both buses go there; he needs the faster one, which is the direct number seven.',
  },
  {
    ...task(), ...MEET,
    prompt: '学生は　この　あと　何を　しなければ　なりませんか。',
    narration: [
      { speaker: 'narrator', text: '大学で　先生が　話しています。学生は　この　あと　何を　しなければ　なりませんか。', pauseAfter: 700 },
      { speaker: 'a', text: '来週の　発表は　三人一組です。テーマは　こちらで　決めますので　考えなくて　結構です。', pauseAfter: 300 },
      { speaker: 'a', text: 'ただし、グループは　自分たちで　作って、金曜までに　名簿を　出して　ください。', pauseAfter: 600 },
      { speaker: 'narrator', text: '学生は　この　あと　何を　しなければ　なりませんか。' },
    ],
    options: ['グループを　作って　名簿を　出す', 'テーマを　考える', '発表の　資料を　作る', '先生に　相談する'],
    note: '考えなくて結構です removes one task; ただし introduces the one that remains.',
  },
  {
    ...task(), ...WEATHER,
    prompt: '係の人は　この　あと　まず　何を　しますか。',
    narration: [
      { speaker: 'narrator', text: '公園で　二人が　話しています。係の人は　この　あと　まず　何を　しますか。', pauseAfter: 700 },
      { speaker: 'a', text: '午後から　風が　強く　なるそうです。テントは　どうしますか。', pauseAfter: 300 },
      { speaker: 'b', text: '片づけるのは　もったいないので、まず　ロープで　しっかり　固定します。', pauseAfter: 300 },
      { speaker: 'a', text: 'それでも　危なければ　片づけましょう。', pauseAfter: 600 },
      { speaker: 'narrator', text: '係の人は　この　あと　まず　何を　しますか。' },
    ],
    options: ['テントを　ロープで　固定する', 'テントを　片づける', 'イベントを　中止する', '風を　待つ'],
    note: 'Taking the tent down is the fallback if securing it is not enough. まず asks for the first action.',
  },
  {
    ...task(), ...MEET,
    prompt: '女の人は　どう　しますか。',
    narration: [
      { speaker: 'narrator', text: '会社で　二人が　話しています。女の人は　どう　しますか。', pauseAfter: 700 },
      { speaker: 'a', text: 'プリンターが　動かないんです。修理を　呼びましょうか。', pauseAfter: 300 },
      { speaker: 'b', text: '紙詰まりかも　しれません。一度　開けて　確認して　みて　ください。', pauseAfter: 300 },
      { speaker: 'a', text: 'わかりました。それで　だめなら　連絡します。', pauseAfter: 600 },
      { speaker: 'narrator', text: '女の人は　どう　しますか。' },
    ],
    options: ['プリンターを　開けて　確認する', '修理を　呼ぶ', '新しい　プリンターを　買う', '紙を　補充する'],
    note: 'Calling for repair is conditional on the check failing, so the check comes first.',
  },
  {
    ...task(), ...SHOP,
    prompt: '男の人は　いつ　取りに　来ますか。',
    narration: [
      { speaker: 'narrator', text: '店で　男の人と　店員が　話しています。男の人は　いつ　取りに　来ますか。', pauseAfter: 700 },
      { speaker: 'a', text: 'この　時計、修理に　どのくらい　かかりますか。', pauseAfter: 300 },
      { speaker: 'b', text: '通常は　一週間ですが、お急ぎでしたら　三日で　できます。追加料金が　かかりますが。', pauseAfter: 300 },
      { speaker: 'a', text: '来週　出張なので、お願いします。', pauseAfter: 600 },
      { speaker: 'narrator', text: '男の人は　いつ　取りに　来ますか。' },
    ],
    options: ['三日後', '一週間後', '来週', '明日'],
    note: 'The business trip next week is why he pays extra for the three-day option.',
  },
  {
    ...task(), ...STATION,
    prompt: '女の人は　この　あと　どう　しますか。',
    narration: [
      { speaker: 'narrator', text: '駅で　女の人と　駅員が　話しています。女の人は　この　あと　どう　しますか。', pauseAfter: 700 },
      { speaker: 'a', text: '定期券を　買いたいんですが。', pauseAfter: 300 },
      { speaker: 'b', text: '定期券は　二階の　窓口です。ただ、今は　混んで　いますので　機械の　ほうが　早いですよ。', pauseAfter: 300 },
      { speaker: 'a', text: '時間が　ないので　そちらに　します。', pauseAfter: 600 },
      { speaker: 'narrator', text: '女の人は　この　あと　どう　しますか。' },
    ],
    options: ['機械で　買う', '二階の　窓口で　買う', '明日　また　来る', '並んで　待つ'],
    note: 'そちら points at the machine, which the staff member recommended because the counter is busy.',
  },

  /* ---------- ポイント理解 ---------- */
  {
    ...point(), ...MEET,
    prompt: '男の人は　どうして　この　会社を　選びましたか。',
    narration: [
      { speaker: 'narrator', text: '会社で　二人が　話しています。男の人は　どうして　この　会社を　選びましたか。', pauseAfter: 700 },
      { speaker: 'a', text: '給料が　いいから　決めたんですか。', pauseAfter: 300 },
      { speaker: 'b', text: 'いえ、それは　あまり。研修が　しっかりして　いるところに　ひかれました。', pauseAfter: 600 },
      { speaker: 'narrator', text: '男の人は　どうして　この　会社を　選びましたか。' },
    ],
    options: ['研修が　しっかりして　いるから', '給料が　いいから', '家から　近いから', '友だちが　いるから'],
    note: 'いえ、それはあまり dismisses salary. The reason follows immediately after.',
  },
  {
    ...point(), ...SHOP,
    prompt: '女の人は　何が　問題だと　言って　いますか。',
    narration: [
      { speaker: 'narrator', text: '店で　二人が　話しています。女の人は　何が　問題だと　言って　いますか。', pauseAfter: 700 },
      { speaker: 'a', text: 'この　ソファ、色も　形も　いいですね。', pauseAfter: 300 },
      { speaker: 'b', text: 'ええ。値段も　思ったより　安いです。ただ、うちの　ドアから　入るかどうか。', pauseAfter: 600 },
      { speaker: 'narrator', text: '女の人は　何が　問題だと　言って　いますか。' },
    ],
    options: ['家に　運び入れられるか　どうか', '値段が　高い　こと', '色が　合わない　こと', '形が　好みでない　こと'],
    note: 'Three positives are listed before ただ introduces the single real concern.',
  },
  {
    ...point(), ...WEATHER,
    prompt: '週末の　イベントは　どう　なりますか。',
    narration: [
      { speaker: 'narrator', text: '天気の　話を　して　います。週末の　イベントは　どう　なりますか。', pauseAfter: 700 },
      { speaker: 'a', text: '土曜は　雨の　予報ですね。中止でしょうか。', pauseAfter: 300 },
      { speaker: 'b', text: '屋根の　ある　会場なので　やります。ただ、駐車場が　使えなく　なるかも　しれません。', pauseAfter: 600 },
      { speaker: 'narrator', text: '週末の　イベントは　どう　なりますか。' },
    ],
    options: ['予定どおり　行われる', '中止に　なる', '来週に　延期される', '会場が　変更に　なる'],
    note: 'The venue is covered, so rain does not stop it. The parking issue is a side detail, not a cancellation.',
  },
  {
    ...point(), ...MEET,
    prompt: '女の人は　何に　困って　いますか。',
    narration: [
      { speaker: 'narrator', text: '大学で　二人が　話しています。女の人は　何に　困って　いますか。', pauseAfter: 700 },
      { speaker: 'a', text: 'レポート、テーマは　決まった？', pauseAfter: 300 },
      { speaker: 'b', text: 'テーマは　すぐ　決まったんだけど、参考に　なる　本が　図書館に　なくて。', pauseAfter: 600 },
      { speaker: 'narrator', text: '女の人は　何に　困って　いますか。' },
    ],
    options: ['資料が　見つからない　こと', 'テーマが　決まらない　こと', '時間が　足りない　こと', '書き方が　わからない　こと'],
    note: 'The topic was easy; the trouble is finding source material.',
  },
  {
    ...point(), ...STATION,
    prompt: '男の人は　何を　なくしましたか。',
    narration: [
      { speaker: 'narrator', text: '駅で　男の人と　駅員が　話しています。男の人は　何を　なくしましたか。', pauseAfter: 700 },
      { speaker: 'a', text: '黒い　かばんを　忘れたかも　しれません。', pauseAfter: 300 },
      { speaker: 'b', text: 'かばんは　こちらに　届いて　いますよ。中身を　ご確認ください。', pauseAfter: 300 },
      { speaker: 'a', text: 'あ、かばんは　ありました。でも　中の　手帳が　見当たりません。', pauseAfter: 600 },
      { speaker: 'narrator', text: '男の人は　何を　なくしましたか。' },
    ],
    options: ['手帳', 'かばん', '財布', '切符'],
    note: 'The bag was found. What is actually missing is the notebook inside it.',
  },
  {
    ...point(), ...MEET,
    prompt: '二人は　何時に　集合しますか。',
    narration: [
      { speaker: 'narrator', text: '二人が　話しています。二人は　何時に　集合しますか。', pauseAfter: 700 },
      { speaker: 'a', text: '映画は　七時からだから、六時半に　駅で　どう？', pauseAfter: 300 },
      { speaker: 'b', text: 'チケットを　買う　時間も　いるから、もう　十五分　早いほうが　いいな。', pauseAfter: 300 },
      { speaker: 'a', text: 'じゃあ　そうしよう。', pauseAfter: 600 },
      { speaker: 'narrator', text: '二人は　何時に　集合しますか。' },
    ],
    options: ['六時十五分', '六時半', '七時', '六時四十五分'],
    note: 'Fifteen minutes earlier than 6:30 is 6:15 — the arithmetic is the question.',
  },
  {
    ...point(), ...SHOP,
    prompt: '店は　いつから　休みますか。',
    narration: [
      { speaker: 'narrator', text: '店の　お知らせを　聞いて　います。店は　いつから　休みますか。', pauseAfter: 700 },
      { speaker: 'a', text: '当店は　工事の　ため、今月末から　しばらく　休業いたします。', pauseAfter: 300 },
      { speaker: 'a', text: 'なお、隣の　支店は　通常どおり　営業して　おります。', pauseAfter: 600 },
      { speaker: 'narrator', text: 'この　店は　いつから　休みますか。' },
    ],
    options: ['今月の　終わり', '来月の　初め', '今週末', '工事が　終わってから'],
    note: '今月末 means the end of this month. The branch information is a distractor.',
  },
  {
    ...point(), ...MEET,
    prompt: '男の人は　どうして　断りましたか。',
    narration: [
      { speaker: 'narrator', text: '会社で　二人が　話しています。男の人は　どうして　断りましたか。', pauseAfter: 700 },
      { speaker: 'a', text: '転勤の　話、断ったそうですね。家族の　都合ですか。', pauseAfter: 300 },
      { speaker: 'b', text: '家族は　賛成して　くれたんです。今の　仕事を　最後まで　やりたくて。', pauseAfter: 600 },
      { speaker: 'narrator', text: '男の人は　どうして　断りましたか。' },
    ],
    options: ['今の　仕事を　続けたいから', '家族が　反対したから', '給料が　下がるから', '引っ越しが　嫌だから'],
    note: 'The family angle is raised and then explicitly ruled out.',
  },

  /* ---------- 概要理解 ---------- */
  {
    ...summary(), ...MEET, revealAfterAudio: true,
    prompt: '話の　主な　内容は　何ですか。',
    narration: [
      { speaker: 'narrator', text: '会社で　担当者が　話して　います。', pauseAfter: 600 },
      { speaker: 'a', text: '来月から　会議の　やり方を　変えます。これまでは　全員が　集まって　いましたが、これからは　関係者だけで　行います。', pauseAfter: 300 },
      { speaker: 'a', text: '内容は　記録に　残し、誰でも　あとから　読めるように　します。時間を　減らしながら、情報は　全員に　届くように　したいのです。', pauseAfter: 600 },
      { speaker: 'narrator', text: '話の　主な　内容は　何ですか。' },
    ],
    options: ['会議の　やり方を　変える　こと', '会議を　やめる　こと', '記録を　取る　人を　決める　こと', '会議室を　変更する　こと'],
    note: 'The record-keeping is one part of the change, not the point itself. 概要理解 asks for the whole, not a detail.',
  },
  {
    ...summary(), ...SHOP, revealAfterAudio: true,
    prompt: '店員は　何に　ついて　話して　いますか。',
    narration: [
      { speaker: 'narrator', text: '店で　店員が　話して　います。', pauseAfter: 600 },
      { speaker: 'a', text: '今週から　袋が　有料に　なりました。一枚　五円　いただきます。', pauseAfter: 300 },
      { speaker: 'a', text: 'ご自分の　袋を　お持ちの　方には　ポイントを　差し上げて　おりますので、ぜひ　ご利用ください。', pauseAfter: 600 },
      { speaker: 'narrator', text: '店員は　何に　ついて　話して　いますか。' },
    ],
    options: ['袋の　新しい　ルール', 'ポイントカードの　作り方', '商品の　値上げ', '店の　営業時間'],
    note: 'Both halves are about bags — the charge and the incentive to bring your own.',
  },
  {
    ...summary(), ...WEATHER, revealAfterAudio: true,
    prompt: '話の　主な　内容は　何ですか。',
    narration: [
      { speaker: 'narrator', text: 'ラジオで　話して　います。', pauseAfter: 600 },
      { speaker: 'a', text: 'この　地域では　夏の　水不足が　続いて　います。今年も　雨が　少なく、川の　水位が　下がって　います。', pauseAfter: 300 },
      { speaker: 'a', text: '各家庭でも、お風呂の　水を　洗濯に　使うなど、できる　ことから　始めて　いただきたいと　思います。', pauseAfter: 600 },
      { speaker: 'narrator', text: '話の　主な　内容は　何ですか。' },
    ],
    options: ['家庭でも　水を　大切に　使って　ほしい　こと', '今年の　夏が　暑くなる　こと', '川の　工事が　始まる　こと', '洗濯機の　選び方'],
    note: 'The situation is background; the request to households is what the speaker is driving at.',
  },
  {
    ...summary(), ...STATION, revealAfterAudio: true,
    prompt: '何に　ついての　お知らせですか。',
    narration: [
      { speaker: 'narrator', text: '駅で　放送が　流れて　います。', pauseAfter: 600 },
      { speaker: 'a', text: '来月から　この　駅の　エレベーターの　工事を　行います。工事中は　北口の　エレベーターが　使えません。', pauseAfter: 300 },
      { speaker: 'a', text: '南口の　ものは　ご利用いただけますので、お手数ですが　そちらへ　お回りください。', pauseAfter: 600 },
      { speaker: 'narrator', text: '何に　ついての　お知らせですか。' },
    ],
    options: ['エレベーターが　一部　使えなく　なる　こと', '駅が　閉まる　こと', '電車が　遅れる　こと', '新しい　出口が　できる　こと'],
    note: 'Only one lift closes; the station stays open. The announcement is about restricted access.',
  },
  {
    ...summary(), ...MEET, revealAfterAudio: true,
    prompt: '先生は　何を　伝えたいのですか。',
    narration: [
      { speaker: 'narrator', text: '学校で　先生が　話して　います。', pauseAfter: 600 },
      { speaker: 'a', text: '発表の　準備で　大切なのは、うまく　話す　ことでは　ありません。', pauseAfter: 300 },
      { speaker: 'a', text: '聞く人が　何を　知りたいかを　考える　ことです。それが　決まれば、話す　順番も　自然に　決まります。', pauseAfter: 600 },
      { speaker: 'narrator', text: '先生は　何を　伝えたいのですか。' },
    ],
    options: ['聞く人の　立場で　考える　ことが　大切だ', '話し方の　練習を　する　ことが　大切だ', '発表の　時間を　守る　ことが　大切だ', '資料を　多く　作る　ことが　大切だ'],
    note: 'The first sentence rules out delivery skill; the second states the actual point.',
  },
  {
    ...summary(), ...SHOP, revealAfterAudio: true,
    prompt: '話の　主な　内容は　何ですか。',
    narration: [
      { speaker: 'narrator', text: '食事会で　男の人が　話して　います。', pauseAfter: 600 },
      { speaker: 'a', text: '料理を　習い始めて　一年に　なります。最初は　レシピどおりに　作る　ことしか　できませんでした。', pauseAfter: 300 },
      { speaker: 'a', text: '今は　冷蔵庫に　ある　ものを　見て、何が　作れるか　考えられるように　なりました。', pauseAfter: 600 },
      { speaker: 'narrator', text: '話の　主な　内容は　何ですか。' },
    ],
    options: ['料理の　力が　ついてきた　こと', 'レシピ本を　集めて　いる　こと', '料理教室が　安い　こと', '冷蔵庫を　買いかえた　こと'],
    note: 'The contrast between "only from recipes" and "now improvising" is the growth being described.',
  },
  {
    ...summary(), ...MEET, revealAfterAudio: true,
    prompt: '女の人は　何に　ついて　話して　いますか。',
    narration: [
      { speaker: 'narrator', text: '会社で　女の人が　話して　います。', pauseAfter: 600 },
      { speaker: 'a', text: '在宅勤務を　始めて　半年　経ちました。通勤が　なくなった　分、時間には　余裕が　できました。', pauseAfter: 300 },
      { speaker: 'a', text: 'ただ、同僚と　ちょっと　話す　機会が　減り、相談が　遅れる　ことが　あります。', pauseAfter: 600 },
      { speaker: 'narrator', text: '女の人は　何に　ついて　話して　いますか。' },
    ],
    options: ['在宅勤務の　よい点と　困る点', '通勤が　大変だった　こと', '会社を　やめたい　こと', '同僚との　けんか'],
    note: 'ただ pivots from the benefit to the drawback: both sides together are the topic.',
  },
  {
    ...summary(), ...WEATHER, revealAfterAudio: true,
    prompt: '話の　主な　内容は　何ですか。',
    narration: [
      { speaker: 'narrator', text: '市の　放送が　流れて　います。', pauseAfter: 600 },
      { speaker: 'a', text: '毎年　この　時期は　落ち葉が　多く、道が　すべりやすく　なって　います。', pauseAfter: 300 },
      { speaker: 'a', text: '特に　朝は　ぬれて　いますので、自転車の　方は　速度を　落として　お通り　ください。', pauseAfter: 600 },
      { speaker: 'narrator', text: '話の　主な　内容は　何ですか。' },
    ],
    options: ['道が　すべるので　気を　つけて　ほしい　こと', '落ち葉を　拾って　ほしい　こと', '自転車を　使わないで　ほしい　こと', '道路工事の　お知らせ'],
    note: 'It asks cyclists to slow down, not to stop riding. Watch the difference between caution and prohibition.',
  },

  /* ---------- 発話表現 ---------- */
  { ...speech(), ...MEET, prompt: 'この　場面で　何と　言いますか。',
    narration: [{ speaker: 'narrator', text: '先輩に　仕事の　やり方を　教えて　ほしいです。何と　言いますか。' }],
    options: ['お忙しい　ところ　すみません、教えて　いただけますか。', 'お忙しい　ところ　すみません、教えて　あげますか。', 'お忙しい　ですね、教えましょうか。', '教えて　もらいましたか。'],
    note: 'A request to a senior opens by acknowledging their time, then uses ～ていただけますか.' },
  { ...speech(), ...MEET, prompt: 'この　場面で　何と　言いますか。',
    narration: [{ speaker: 'narrator', text: '同僚が　資料を　手伝って　くれました。何と　言いますか。' }],
    options: ['助かりました。ありがとうございます。', '助けましょうか。ありがとうございます。', 'お世話しました。', '手伝って　あげました。'],
    note: '助かりました thanks someone for the difference their help made.' },
  { ...speech(), ...SHOP, prompt: 'この　場面で　何と　言いますか。',
    narration: [{ speaker: 'narrator', text: '注文した　料理と　違う　ものが　来ました。店員に　何と　言いますか。' }],
    options: ['すみません、頼んだ　ものと　違うようですが。', 'すみません、これを　頼みましょうか。', 'すみません、これで　いいです。', 'すみません、違いましたね。'],
    note: '～ようですが softens a complaint so it does not sound like an accusation.' },
  { ...speech(), ...STATION, prompt: 'この　場面で　何と　言いますか。',
    narration: [{ speaker: 'narrator', text: '道に　迷って　いる　外国人を　見かけました。何と　言いますか。' }],
    options: ['何か　お困りですか。', '何か　困りましょうか。', '道に　迷いましたね。', 'どこへ　行きましたか。'],
    note: 'お困りですか is the standard way to offer help to a stranger.' },
  { ...speech(), ...MEET, prompt: 'この　場面で　何と　言いますか。',
    narration: [{ speaker: 'narrator', text: '会議で　自分の　意見を　言いたいです。何と　言いますか。' }],
    options: ['よろしければ、一つ　よろしいでしょうか。', 'よろしければ、言って　ください。', '言っても　いいと　思います。', '意見が　ありましたか。'],
    note: 'Asking for the floor politely uses よろしいでしょうか rather than simply starting to talk.' },
  { ...speech(), ...SHOP, prompt: 'この　場面で　何と　言いますか。',
    narration: [{ speaker: 'narrator', text: '友だちの　家で　食事を　いただきます。何と　言いますか。' }],
    options: ['いただきます。', 'ごちそうさまでした。', 'めしあがれ。', 'おかまいなく。'],
    note: 'いただきます opens the meal; めしあがれ is what the host says.' },
  { ...speech(), ...MEET, prompt: 'この　場面で　何と　言いますか。',
    narration: [{ speaker: 'narrator', text: '約束の　時間に　遅れそうです。電話で　何と　言いますか。' }],
    options: ['すみません、十分ほど　遅れそうです。', 'すみません、十分ほど　遅れました。', 'すみません、遅れても　いいですか。', 'すみません、遅れて　ください。'],
    note: '～そうです reports what is about to happen; 遅れました would mean you already arrived late.' },
  { ...speech(), ...STATION, prompt: 'この　場面で　何と　言いますか。',
    narration: [{ speaker: 'narrator', text: '混んだ　電車を　降ります。前に　人が　立って　います。何と　言いますか。' }],
    options: ['すみません、降ります。', 'すみません、乗ります。', 'ちょっと　待って　ください。', 'そこを　どいて　ください。'],
    note: 'すみません、降ります is the set phrase; どいてください is too blunt.' },

  /* ---------- 即時応答 ---------- */
  { ...quick(), ...MEET, prompt: '聞いて、最も　よい　返事を　選んで　ください。',
    narration: [{ speaker: 'a', text: 'その　仕事、私が　やって　おきましょうか。' }],
    options: ['いいんですか。助かります。', 'いいんですか。やって　おきました。', 'ええ、やって　おきましょう。', 'はい、やって　います。'],
    note: '～ておきましょうか offers; the reply checks it is really all right, then thanks.' },
  { ...quick(), ...MEET, prompt: '聞いて、最も　よい　返事を　選んで　ください。',
    narration: [{ speaker: 'a', text: '会議の　資料、もう　目を　通されましたか。' }],
    options: ['いえ、まだ　なんです。', 'いえ、通しました。', 'はい、まだです。', 'ええ、通されました。'],
    note: '目を通す means to look over. 通されました would be the honorific about the listener.' },
  { ...quick(), ...SHOP, prompt: '聞いて、最も　よい　返事を　選んで　ください。',
    narration: [{ speaker: 'a', text: 'もう少し　安く　なりませんか。' }],
    options: ['申し訳ありません、こちらが　精一杯でして。', '申し訳ありません、安く　なりました。', 'はい、高いです。', 'ええ、安く　しませんか。'],
    note: 'A refusal to discount apologises and explains rather than saying no outright.' },
  { ...quick(), ...MEET, prompt: '聞いて、最も　よい　返事を　選んで　ください。',
    narration: [{ speaker: 'a', text: '田中さん、最近　顔色が　よくないね。' }],
    options: ['ちょっと　寝不足で。', 'ちょっと　顔色ですね。', 'ええ、よかったです。', 'いいえ、田中です。'],
    note: 'A concerned observation is answered with the reason behind it.' },
  { ...quick(), ...STATION, prompt: '聞いて、最も　よい　返事を　選んで　ください。',
    narration: [{ speaker: 'a', text: 'この　席、空いて　いますか。' }],
    options: ['ええ、どうぞ。', 'ええ、座りました。', 'いいえ、席です。', 'はい、空けます。'],
    note: 'A question about a free seat is answered by inviting the person to sit.' },
  { ...quick(), ...MEET, prompt: '聞いて、最も　よい　返事を　選んで　ください。',
    narration: [{ speaker: 'a', text: '明日の　打ち合わせ、時間を　変えて　いただけませんか。' }],
    options: ['何時が　ご都合　よろしいですか。', '何時に　変えましたか。', 'はい、変えて　いただきます。', 'ええ、打ち合わせです。'],
    note: 'A request to reschedule is met by asking what time would suit.' },
  { ...quick(), ...MEET, prompt: '聞いて、最も　よい　返事を　選んで　ください。',
    narration: [{ speaker: 'a', text: 'この　字、読めますか。' }],
    options: ['ちょっと　わかりませんね。', 'ちょっと　読みました。', 'はい、字です。', 'いいえ、読みましょう。'],
    note: 'When you cannot read something, わかりません is softer than いいえ.' },
  { ...quick(), ...SHOP, prompt: '聞いて、最も　よい　返事を　選んで　ください。',
    narration: [{ speaker: 'a', text: '試着して　みても　いいですか。' }],
    options: ['はい、あちらの　試着室を　どうぞ。', 'はい、試着しました。', 'いいえ、着ましょうか。', 'ええ、試着室です。'],
    note: 'Permission is granted by pointing the customer to where they can do it.' },
  { ...quick(), ...MEET, prompt: '聞いて、最も　よい　返事を　選んで　ください。',
    narration: [{ speaker: 'a', text: 'お子さん、もう　小学生ですか。' }],
    options: ['ええ、この　春から。', 'ええ、小学生でした。', 'いいえ、子どもです。', 'はい、行きましょう。'],
    note: 'この春から fills in when it started, which is what the question is really after.' },
  { ...quick(), ...STATION, prompt: '聞いて、最も　よい　返事を　選んで　ください。',
    narration: [{ speaker: 'a', text: '傘、お持ちですか。' }],
    options: ['あ、忘れて　きました。', 'あ、持ちましょうか。', 'はい、傘です。', 'いいえ、持ちました。'],
    note: 'お持ちですか asks whether you have one; the reply says you left it behind.' },
  { ...quick(), ...MEET, prompt: '聞いて、最も　よい　返事を　選んで　ください。',
    narration: [{ speaker: 'a', text: 'さっきの　説明、わかりにくかったですか。' }],
    options: ['いえ、よく　わかりました。', 'いえ、わかりにくいです。', 'はい、説明しました。', 'ええ、わかりましょう。'],
    note: 'The speaker is checking their own explanation, so the reply reassures them.' },
  { ...quick(), ...MEET, prompt: '聞いて、最も　よい　返事を　選んで　ください。',
    narration: [{ speaker: 'a', text: '週末、どこかへ　出かけましたか。' }],
    options: ['ええ、久しぶりに　海へ。', 'ええ、出かけましょう。', 'いいえ、週末です。', 'はい、どこかです。'],
    note: 'A yes answer names where you went rather than repeating the question word.' },
];

export const listeningScripts: Record<Level, Script[]> = { N5: n5, N4: n4, N3: n3, N2: [], N1: [] };
export { task, point, quick, speech, summary, integrated, SHOP, MEET, STATION, WEATHER };
