import type { Level } from './levels';
import type { Script } from './listening-scripts.ts';

/**
 * Listening scripts added after the original 234.
 *
 * They live apart from listening-scripts.ts for one reason: saved progress is
 * keyed by a question's index in its level's bank, and the main listening pool
 * is spliced into the middle of the assembly in course-data.ts. Adding there
 * would shift every reading, 文章の文法 and 語彙 item after it. These are
 * appended at the end instead.
 *
 * Conventions are the same as the main pool: options[0] is the answer, 概要理解
 * sets revealAfterAudio via the builder, and speakers are 'man'/'woman' — the
 * one who answers the question, or performs the action it asks about, carries
 * the gender the question names.
 */
const task = (jp = '課題理解') => ({ jp, itemType: 'Task comprehension' });
const point = (jp = 'ポイント理解') => ({ jp, itemType: 'Point comprehension' });
const quick = (jp = '即時応答') => ({ jp, itemType: 'Quick response' });
const summary = (jp = '概要理解') => ({ jp, itemType: 'Summary comprehension' });
const integrated = (jp = '統合理解') => ({ jp, itemType: 'Integrated listening' });

export const extraListeningScripts: Record<Level, Script[]> = {
  N5: [
{
    ...task(),
    prompt: 'おんなの人は　なにを　かいますか。',
    narration: [
      { speaker: 'narrator', text: 'みせで　おんなの人と　てんいんが　はなして　います。おんなの人は　なにを　かいますか。', pauseAfter: 800 },
      { speaker: 'woman', text: 'りんごを　みっつ　ください。', pauseAfter: 350 },
      { speaker: 'man', text: 'すみません、りんごは　ありません。みかんは　いかがですか。', pauseAfter: 350 },
      { speaker: 'woman', text: 'じゃあ、それを　ふたつ　ください。', pauseAfter: 700 },
      { speaker: 'narrator', text: 'おんなの人は　なにを　かいますか。' },
    ],
    options: ['みかんを　ふたつ', 'りんごを　みっつ', 'みかんを　みっつ', 'りんごを　ふたつ'],
    note: 'それ points at the mandarins offered in place of the apples, and the number changes too.',
  },
  {
    ...task(),
    prompt: 'おとこの人は　これから　なにを　しますか。',
    narration: [
      { speaker: 'narrator', text: 'がっこうで　ふたりが　はなして　います。おとこの人は　これから　なにを　しますか。', pauseAfter: 800 },
      { speaker: 'woman', text: 'この　ほんを　としょかんに　かえして　きて　ください。', pauseAfter: 350 },
      { speaker: 'man', text: 'はい。その　まえに　きょうしつの　でんきを　けします。', pauseAfter: 700 },
      { speaker: 'narrator', text: 'おとこの人は　これから　なにを　しますか。' },
    ],
    options: ['でんきを　けします', 'ほんを　かえします', 'としょかんへ　いきます', 'きょうしつを　そうじします'],
    note: 'その まえに puts the lights first even though the book was asked for first.',
  },
  {
    ...task(),
    prompt: 'おんなの人は　なんじに　いきますか。',
    narration: [
      { speaker: 'narrator', text: 'ふたりが　はなして　います。おんなの人は　なんじに　いきますか。', pauseAfter: 800 },
      { speaker: 'man', text: 'あした　ごぜん　くじに　きて　ください。', pauseAfter: 350 },
      { speaker: 'woman', text: 'くじは　でんしゃが　こんで　います。じゅうじでも　いいですか。', pauseAfter: 350 },
      { speaker: 'man', text: 'いいですよ。', pauseAfter: 700 },
      { speaker: 'narrator', text: 'おんなの人は　なんじに　いきますか。' },
    ],
    options: ['じゅうじ', 'くじ', 'はちじ', 'じゅういちじ'],
    note: 'The first time is rejected and the second is agreed.',
  },
  {
    ...task(),
    prompt: 'おとこの人は　どこへ　いきますか。',
    narration: [
      { speaker: 'narrator', text: 'えきで　おとこの人と　えきいんが　はなして　います。おとこの人は　どこへ　いきますか。', pauseAfter: 800 },
      { speaker: 'man', text: 'すみません、トイレは　どこですか。', pauseAfter: 350 },
      { speaker: 'woman', text: 'かいさつの　そとです。にかいにも　ありますよ。', pauseAfter: 350 },
      { speaker: 'man', text: 'ちかい　ほうが　いいです。にかいへ　いきます。', pauseAfter: 700 },
      { speaker: 'narrator', text: 'おとこの人は　どこへ　いきますか。' },
    ],
    options: ['にかい', 'かいさつの　そと', 'えきの　まえ', 'いちかい'],
    note: 'Two places are offered and he names the one he chooses.',
  },
  {
    ...point(),
    prompt: 'おんなの人は　なにが　すきですか。',
    narration: [
      { speaker: 'narrator', text: 'ふたりが　はなして　います。おんなの人は　なにが　すきですか。', pauseAfter: 800 },
      { speaker: 'man', text: 'にくが　すきですか。', pauseAfter: 350 },
      { speaker: 'woman', text: 'にくは　あまり。さかなが　すきです。', pauseAfter: 700 },
      { speaker: 'narrator', text: 'おんなの人は　なにが　すきですか。' },
    ],
    options: ['さかな', 'にく', 'やさい', 'くだもの'],
    note: 'あまり with a trailing pause means "not much", so the next item is the answer.',
  },
  {
    ...point(),
    prompt: 'おとこの人は　なんで　きましたか。',
    narration: [
      { speaker: 'narrator', text: 'ふたりが　はなして　います。おとこの人は　なんで　きましたか。', pauseAfter: 800 },
      { speaker: 'woman', text: 'でんしゃで　きましたか。', pauseAfter: 350 },
      { speaker: 'man', text: 'いいえ、きょうは　じてんしゃで　きました。', pauseAfter: 700 },
      { speaker: 'narrator', text: 'おとこの人は　なんで　きましたか。' },
    ],
    options: ['じてんしゃ', 'でんしゃ', 'バス', 'あるいて'],
    note: 'いいえ denies the first guess and the real means follows.',
  },
  {
    ...point(),
    prompt: 'おんなの人は　どこに　すんで　いますか。',
    narration: [
      { speaker: 'narrator', text: 'ふたりが　はなして　います。おんなの人は　どこに　すんで　いますか。', pauseAfter: 800 },
      { speaker: 'man', text: 'とうきょうに　すんで　いますか。', pauseAfter: 350 },
      { speaker: 'woman', text: 'まえは　とうきょうでした。いまは　よこはまに　すんで　います。', pauseAfter: 700 },
      { speaker: 'narrator', text: 'おんなの人は　どこに　すんで　いますか。' },
    ],
    options: ['よこはま', 'とうきょう', 'おおさか', 'きょうと'],
    note: 'まえは marks the old place; いまは marks the current one.',
  },
  {
    ...point(),
    prompt: 'おとこの人は　なんようびが　やすみですか。',
    narration: [
      { speaker: 'narrator', text: 'ふたりが　はなして　います。おとこの人は　なんようびが　やすみですか。', pauseAfter: 800 },
      { speaker: 'woman', text: 'にちようびが　やすみですか。', pauseAfter: 350 },
      { speaker: 'man', text: 'にちようびは　しごとです。すいようびが　やすみです。', pauseAfter: 700 },
      { speaker: 'narrator', text: 'おとこの人は　なんようびが　やすみですか。' },
    ],
    options: ['すいようび', 'にちようび', 'どようび', 'げつようび'],
    note: 'The guessed day is where he works; the free day is named afterwards.',
  },
  { ...quick(), prompt: 'きいて、いちばん　いい　へんじを　えらんで　ください。',
    narration: [{ speaker: 'woman', text: 'おなまえは　なんですか。' }],
    options: ['たなかです。', 'にほんです。', 'はい、そうです。', 'よんじゅうです。'],
    note: 'なまえ asks for a name, not a country, a yes or a number.' },
  { ...quick(), prompt: 'きいて、いちばん　いい　へんじを　えらんで　ください。',
    narration: [{ speaker: 'man', text: 'まいにち　なんじに　ねますか。' }],
    options: ['じゅういちじごろです。', 'はちじかんです。', 'まいにちです。', 'ねました。'],
    note: 'なんじ asks a clock time; はちじかん would be a duration.' },
  { ...quick(), prompt: 'きいて、いちばん　いい　へんじを　えらんで　ください。',
    narration: [{ speaker: 'woman', text: 'この　みせは　なんじまでですか。' }],
    options: ['はちじまでです。', 'はちじからです。', 'みせです。', 'はい、そうです。'],
    note: 'まで asks for a closing time, so から would answer the wrong half.' },
  { ...quick(), prompt: 'きいて、いちばん　いい　へんじを　えらんで　ください。',
    narration: [{ speaker: 'man', text: 'いっしょに　えいがを　みませんか。' }],
    options: ['いいですね、いきましょう。', 'はい、みました。', 'いいえ、えいがです。', 'ええ、みて　います。'],
    note: '～ませんか invites, so the reply accepts with a suggestion.' },
  { ...quick(), prompt: 'きいて、いちばん　いい　へんじを　えらんで　ください。',
    narration: [{ speaker: 'woman', text: 'どようびは　なにを　しましたか。' }],
    options: ['ともだちと　かいものを　しました。', 'どようびです。', 'はい、しました。', 'あした　します。'],
    note: 'A past-tense question takes a past-tense report of what was done.' },
  { ...quick(), prompt: 'きいて、いちばん　いい　へんじを　えらんで　ください。',
    narration: [{ speaker: 'man', text: 'この　へやは　さむいですね。' }],
    options: ['ええ、まどを　しめましょうか。', 'はい、さむくしました。', 'いいえ、へやです。', 'ええ、あついですね。'],
    note: 'A ～ですね comment invites agreement plus a practical offer.' },
  { ...quick(), prompt: 'きいて、いちばん　いい　へんじを　えらんで　ください。',
    narration: [{ speaker: 'woman', text: 'すみません、もういちど　おねがいします。' }],
    options: ['はい、ゆっくり　いいますね。', 'はい、おねがいしました。', 'いいえ、いちどです。', 'ええ、ねがいます。'],
    note: 'A request to repeat is answered by agreeing to say it again slowly.' },
  ],
  N4: [
{
    ...task(),
    prompt: '女の人は　このあと　何を　しますか。',
    narration: [
      { speaker: 'narrator', text: '会社で　二人が　話して　います。女の人は　このあと　何を　しますか。', pauseAfter: 700 },
      { speaker: 'woman', text: 'コピー機の　紙が　なくなりました。買いに　行きましょうか。', pauseAfter: 300 },
      { speaker: 'man', text: '倉庫に　まだ　ありますよ。取って　きて　ください。', pauseAfter: 650 },
      { speaker: 'narrator', text: '女の人は　このあと　何を　しますか。' },
    ],
    options: ['倉庫から　紙を　取って　くる', '紙を　買いに　行く', 'コピーを　する', '倉庫を　片づける'],
    note: 'Buying is unnecessary because stock exists, so fetching it is the task.',
  },
  {
    ...task(),
    prompt: '男の人は　何を　注文しますか。',
    narration: [
      { speaker: 'narrator', text: '店で　男の人と　店員が　話して　います。男の人は　何を　注文しますか。', pauseAfter: 700 },
      { speaker: 'man', text: 'カレーと　サラダを　お願いします。', pauseAfter: 300 },
      { speaker: 'woman', text: 'すみません、サラダは　終わって　しまいました。スープなら　ございます。', pauseAfter: 300 },
      { speaker: 'man', text: 'じゃあ　それを　つけて　ください。', pauseAfter: 650 },
      { speaker: 'narrator', text: '男の人は　何を　注文しますか。' },
    ],
    options: ['カレーと　スープ', 'カレーと　サラダ', 'サラダだけ', 'スープだけ'],
    note: 'それ points at the soup the clerk has just offered in place of the salad.',
  },
  {
    ...task(),
    prompt: '二人は　どこで　待ち合わせますか。',
    narration: [
      { speaker: 'narrator', text: '二人が　電話で　話して　います。二人は　どこで　待ち合わせますか。', pauseAfter: 700 },
      { speaker: 'man', text: '駅の　北口で　いいですか。', pauseAfter: 300 },
      { speaker: 'woman', text: '北口は　工事中です。南口に　しませんか。', pauseAfter: 300 },
      { speaker: 'man', text: 'いいですよ。', pauseAfter: 650 },
      { speaker: 'narrator', text: '二人は　どこで　待ち合わせますか。' },
    ],
    options: ['南口', '北口', '改札の　中', '公園'],
    note: 'The first place is ruled out by construction and the second is agreed.',
  },
  {
    ...task(),
    prompt: '女の人は　まず　何を　しますか。',
    narration: [
      { speaker: 'narrator', text: '家で　二人が　話して　います。女の人は　まず　何を　しますか。', pauseAfter: 700 },
      { speaker: 'woman', text: '買い物に　行って　から　洗濯を　します。', pauseAfter: 300 },
      { speaker: 'man', text: '雨が　降りそうですよ。洗濯を　先に　した　ほうが　いいです。', pauseAfter: 300 },
      { speaker: 'woman', text: 'そうですね。そう　します。', pauseAfter: 650 },
      { speaker: 'narrator', text: '女の人は　まず　何を　しますか。' },
    ],
    options: ['洗濯を　する', '買い物に　行く', '掃除を　する', '出かける'],
    note: 'The order is reversed on advice she accepts, so the laundry comes first.',
  },
  {
    ...point(),
    prompt: '男の人は　どうして　来ませんでしたか。',
    narration: [
      { speaker: 'narrator', text: '二人が　話して　います。男の人は　どうして　来ませんでしたか。', pauseAfter: 700 },
      { speaker: 'woman', text: '昨日の　会、具合が　悪かったんですか。', pauseAfter: 300 },
      { speaker: 'man', text: '元気でしたよ。仕事が　終わらなくて　行けませんでした。', pauseAfter: 650 },
      { speaker: 'narrator', text: '男の人は　どうして　来ませんでしたか。' },
    ],
    options: ['仕事が　終わらなかったから', '具合が　悪かったから', '忘れて　いたから', '電車が　遅れたから'],
    note: 'The illness guess is denied, and the reason follows.',
  },
  {
    ...point(),
    prompt: '女の人は　何を　買いましたか。',
    narration: [
      { speaker: 'narrator', text: '二人が　話して　います。女の人は　何を　買いましたか。', pauseAfter: 700 },
      { speaker: 'man', text: 'その　かばん、新しいですね。', pauseAfter: 300 },
      { speaker: 'woman', text: 'これは　姉の　です。私が　買ったのは　この　くつなんです。', pauseAfter: 650 },
      { speaker: 'narrator', text: '女の人は　何を　買いましたか。' },
    ],
    options: ['くつ', 'かばん', 'ぼうし', '何も　買って　いない'],
    note: 'The bag is borrowed; what she bought is named afterwards.',
  },
  {
    ...point(),
    prompt: '男の人は　何が　好きだと　言って　いますか。',
    narration: [
      { speaker: 'narrator', text: '二人が　話して　います。男の人は　何が　好きだと　言って　いますか。', pauseAfter: 700 },
      { speaker: 'woman', text: 'スポーツが　好きなんですか。', pauseAfter: 300 },
      { speaker: 'man', text: 'するのは　苦手です。見るのは　好きで、よく　試合を　見に　行きます。', pauseAfter: 650 },
      { speaker: 'narrator', text: '男の人は　何が　好きだと　言って　いますか。' },
    ],
    options: ['スポーツを　見る　こと', 'スポーツを　する　こと', '音楽を　聞く　こと', '本を　読む　こと'],
    note: 'Doing and watching are contrasted, and only one is liked.',
  },
  {
    ...point(),
    prompt: '女の人は　何時に　起きますか。',
    narration: [
      { speaker: 'narrator', text: '二人が　話して　います。女の人は　何時に　起きますか。', pauseAfter: 700 },
      { speaker: 'man', text: '毎朝　六時に　起きるんですか。', pauseAfter: 300 },
      { speaker: 'woman', text: '前は　六時でしたが、今は　三十分　遅く　なりました。', pauseAfter: 650 },
      { speaker: 'narrator', text: '女の人は　何時に　起きますか。' },
    ],
    options: ['六時半', '六時', '五時半', '七時'],
    note: 'Thirty minutes later than six is six-thirty — the change, not the old time.',
  },
  { ...quick(), prompt: '聞いて、いちばん　いい　へんじを　えらんで　ください。',
    narration: [{ speaker: 'woman', text: 'この　荷物、重そうですね。持ちましょうか。' }],
    options: ['ありがとうございます。お願いします。', 'はい、重くしました。', 'いいえ、荷物です。', 'ええ、持ちません。'],
    note: '～ましょうか offers help and is accepted with thanks.' },
  { ...quick(), prompt: '聞いて、いちばん　いい　へんじを　えらんで　ください。',
    narration: [{ speaker: 'man', text: 'あしたの　会議、何時からでしたか。' }],
    options: ['十時からです。', '十時間です。', '会議室です。', 'あしたでした。'],
    note: '何時から asks a starting time, not a duration or a place.' },
  { ...quick(), prompt: '聞いて、いちばん　いい　へんじを　えらんで　ください。',
    narration: [{ speaker: 'woman', text: 'すみません、ペンを　借りても　いいですか。' }],
    options: ['はい、どうぞ。', 'はい、借りました。', 'いいえ、ペンです。', 'ええ、貸しません。'],
    note: '～てもいいですか asks permission, and どうぞ grants it.' },
  { ...quick(), prompt: '聞いて、いちばん　いい　へんじを　えらんで　ください。',
    narration: [{ speaker: 'man', text: '駅まで　どのくらい　かかりますか。' }],
    options: ['歩いて　十分くらいです。', '十時くらいです。', '駅までです。', '電車です。'],
    note: 'どのくらいかかる asks how long it takes, so the answer is a duration.' },
  { ...quick(), prompt: '聞いて、いちばん　いい　へんじを　えらんで　ください。',
    narration: [{ speaker: 'woman', text: '日本の　生活には　もう　慣れましたか。' }],
    options: ['ええ、だいぶ　慣れました。', 'はい、慣れません。', 'いいえ、生活です。', 'ええ、日本でした。'],
    note: 'もう asks whether something has happened yet; the reply reports the degree.' },
  { ...quick(), prompt: '聞いて、いちばん　いい　へんじを　えらんで　ください。',
    narration: [{ speaker: 'man', text: '今日は　ちょっと　寒く　ないですか。' }],
    options: ['そうですね、窓を　閉めましょうか。', 'はい、寒くしました。', 'いいえ、今日です。', 'ええ、暑いですね。'],
    note: 'A negative-form comment invites agreement and a practical suggestion.' },
  ],
  N3: [
{
    ...task(),
    prompt: '女の人は　このあと　まず　何を　しますか。',
    narration: [
      { speaker: 'narrator', text: '会社で　二人が　話しています。女の人は　このあと　まず　何を　しますか。', pauseAfter: 700 },
      { speaker: 'woman', text: '会議室の　鍵、受付に　借りに　行きますね。', pauseAfter: 300 },
      { speaker: 'man', text: '鍵は　もう　借りてあります。椅子が　足りないので　隣から　運んで　ください。', pauseAfter: 650 },
      { speaker: 'narrator', text: '女の人は　このあと　まず　何を　しますか。' },
    ],
    options: ['隣の　部屋から　椅子を　運ぶ', '受付で　鍵を　借りる', '会議室を　掃除する', '資料を　配る'],
    note: 'Her plan is already done by someone else, so the new instruction is the task.',
  },
  {
    ...task(),
    prompt: '男の人は　何を　買いますか。',
    narration: [
      { speaker: 'narrator', text: '店で　男の人と　店員が　話しています。男の人は　何を　買いますか。', pauseAfter: 700 },
      { speaker: 'man', text: 'この　青い　かさは　いくらですか。', pauseAfter: 300 },
      { speaker: 'woman', text: '二千円です。こちらの　折りたたみは　千五百円で、今日は　二割引きに　なります。', pauseAfter: 300 },
      { speaker: 'man', text: 'じゃあ　安い　ほうを　ください。', pauseAfter: 650 },
      { speaker: 'narrator', text: '男の人は　何を　買いますか。' },
    ],
    options: ['折りたたみの　かさ', '青い　かさ', '両方', '何も　買わない'],
    note: 'The discounted folding umbrella is the cheaper one, which is what 安いほう selects.',
  },
  {
    ...task(),
    prompt: '二人は　何時に　会いますか。',
    narration: [
      { speaker: 'narrator', text: '二人が　電話で　話しています。二人は　何時に　会いますか。', pauseAfter: 700 },
      { speaker: 'man', text: '明日の　打ち合わせ、三時で　いいですか。', pauseAfter: 300 },
      { speaker: 'woman', text: '三時は　別の　予定が　あります。一時間　早めて　いただけますか。', pauseAfter: 300 },
      { speaker: 'man', text: 'では　その　時間で。', pauseAfter: 650 },
      { speaker: 'narrator', text: '二人は　何時に　会いますか。' },
    ],
    options: ['二時', '三時', '四時', '一時'],
    note: 'An hour earlier than three is two — the arithmetic is the question.',
  },
  {
    ...task(),
    prompt: '男の人は　このあと　どこへ　行きますか。',
    narration: [
      { speaker: 'narrator', text: '駅で　男の人と　駅員が　話しています。男の人は　このあと　どこへ　行きますか。', pauseAfter: 700 },
      { speaker: 'man', text: '定期券を　買いたいんですが。', pauseAfter: 300 },
      { speaker: 'woman', text: '定期は　二階の　窓口です。ただ、今日は　改装中で、一階の　臨時窓口で　扱っています。', pauseAfter: 300 },
      { speaker: 'man', text: '分かりました。', pauseAfter: 650 },
      { speaker: 'narrator', text: '男の人は　このあと　どこへ　行きますか。' },
    ],
    options: ['一階の　臨時窓口', '二階の　窓口', '改札', '券売機'],
    note: 'The usual counter is named first and then overridden by the temporary arrangement.',
  },
  {
    ...point(),
    prompt: '女の人は　どうして　遅れましたか。',
    narration: [
      { speaker: 'narrator', text: '会社で　二人が　話しています。女の人は　どうして　遅れましたか。', pauseAfter: 700 },
      { speaker: 'man', text: '電車が　止まっていたんですか。', pauseAfter: 300 },
      { speaker: 'woman', text: '電車は　動いていました。家の　鍵が　見つからなくて　探していたんです。', pauseAfter: 650 },
      { speaker: 'narrator', text: '女の人は　どうして　遅れましたか。' },
    ],
    options: ['鍵を　探して　いたから', '電車が　止まったから', '道が　込んで　いたから', '寝坊したから'],
    note: 'The train guess is denied before the real reason is given.',
  },
  {
    ...point(),
    prompt: '男の人は　何が　よかったと　言って　いますか。',
    narration: [
      { speaker: 'narrator', text: '二人が　旅行について　話しています。男の人は　何が　よかったと　言って　いますか。', pauseAfter: 700 },
      { speaker: 'woman', text: '料理が　おいしかったんですか。', pauseAfter: 300 },
      { speaker: 'man', text: '料理は　普通でした。部屋から　海が　見えて、それが　一番　よかったです。', pauseAfter: 650 },
      { speaker: 'narrator', text: '男の人は　何が　よかったと　言って　いますか。' },
    ],
    options: ['部屋から　海が　見えた　こと', '料理が　おいしかった　こと', '値段が　安かった　こと', '駅から　近かった　こと'],
    note: 'The food is called ordinary, and 一番よかった marks the real highlight.',
  },
  {
    ...point(),
    prompt: '女の人は　何が　大変だと　言って　いますか。',
    narration: [
      { speaker: 'narrator', text: '二人が　新しい　仕事について　話しています。女の人は　何が　大変だと　言って　いますか。', pauseAfter: 700 },
      { speaker: 'man', text: '覚える　ことが　多くて　大変ですか。', pauseAfter: 300 },
      { speaker: 'woman', text: '仕事自体は　慣れました。でも　朝が　早くて、それが　つらいです。', pauseAfter: 650 },
      { speaker: 'narrator', text: '女の人は　何が　大変だと　言って　いますか。' },
    ],
    options: ['朝が　早い　こと', '覚える　ことが　多い　こと', '人間関係', '残業が　多い　こと'],
    note: 'でも introduces the actual difficulty after the work itself is dismissed.',
  },
  {
    ...point(),
    prompt: '男の人は　いつ　引っ越しますか。',
    narration: [
      { speaker: 'narrator', text: '二人が　話しています。男の人は　いつ　引っ越しますか。', pauseAfter: 700 },
      { speaker: 'woman', text: '来月　引っ越すんですか。', pauseAfter: 300 },
      { speaker: 'man', text: '来月の　予定でしたが、部屋の　工事が　延びて　再来月に　なりました。', pauseAfter: 650 },
      { speaker: 'narrator', text: '男の人は　いつ　引っ越しますか。' },
    ],
    options: ['再来月', '来月', '今月', '来年'],
    note: 'The first date is the original plan; the change after が is the answer.',
  },
  {
    ...summary(),
    prompt: '話の　主な　内容は　何ですか。',
    narration: [
      { speaker: 'narrator', text: '学校で　先生が　話しています。', pauseAfter: 600 },
      { speaker: 'woman', text: '来週の　遠足ですが、集合場所が　変わります。これまでは　学校の　前でしたが、公園の　入り口に　なりました。', pauseAfter: 300 },
      { speaker: 'woman', text: '時間は　これまでどおり　八時半です。遅れないように　来て　ください。', pauseAfter: 700 },
      { speaker: 'narrator', text: '話の　主な　内容は　何ですか。' },
    ],
    options: ['集合場所が　変わる　こと', '集合時間が　変わる　こと', '遠足が　中止に　なる　こと', '公園が　使えない　こと'],
    note: 'The place changes and the time does not, so the announcement is about the place.',
  },
  {
    ...summary(),
    prompt: '話の　主な　内容は　何ですか。',
    narration: [
      { speaker: 'narrator', text: '店の　お知らせを　聞いて　います。', pauseAfter: 600 },
      { speaker: 'man', text: '本日は　ご来店　ありがとうございます。三階の　催し場では　今週末まで　古本市を　開いて　おります。', pauseAfter: 300 },
      { speaker: 'man', text: '五冊以上　お買い上げの　方には　しおりを　差し上げて　おります。', pauseAfter: 700 },
      { speaker: 'narrator', text: '話の　主な　内容は　何ですか。' },
    ],
    options: ['古本市を　開いて　いる　こと', '店が　今週末で　閉まる　こと', '本が　値上がりする　こと', '三階が　使えない　こと'],
    note: 'The announcement advertises an event, with the gift as a secondary detail.',
  },
  {
    ...summary(),
    prompt: '話の　主な　内容は　何ですか。',
    narration: [
      { speaker: 'narrator', text: 'ラジオで　話して　います。', pauseAfter: 600 },
      { speaker: 'woman', text: '朝ご飯を　食べない　人が　増えて　います。時間が　ないという　理由が　最も　多く　聞かれます。', pauseAfter: 300 },
      { speaker: 'woman', text: 'ですが　前の　晩に　用意して　おけば、朝は　五分で　済みます。手間を　夜に　移すだけで　続けやすく　なります。', pauseAfter: 700 },
      { speaker: 'narrator', text: '話の　主な　内容は　何ですか。' },
    ],
    options: ['前の　晩に　用意すれば　朝食は　続けやすい　こと', '朝食を　食べない　方が　よい　こと', '朝は　時間が　ない　こと', '朝食の　内容を　変える　こと'],
    note: 'The stated obstacle is answered with a concrete remedy, which is the point of the talk.',
  },
  { ...quick(), prompt: '聞いて、いちばん　いい　返事を　選んで　ください。',
    narration: [{ speaker: 'woman', text: 'この　伝票、今日中に　お願いできますか。' }],
    options: ['はい、やって　おきます。', 'はい、お願いしました。', 'いいえ、伝票です。', 'ええ、今日でした。'],
    note: 'A request is accepted with an action commitment.' },
  { ...quick(), prompt: '聞いて、いちばん　いい　返事を　選んで　ください。',
    narration: [{ speaker: 'man', text: 'すみません、この　席　空いて　いますか。' }],
    options: ['ええ、どうぞ。', 'はい、空けました。', 'いいえ、席です。', 'ええ、座りました。'],
    note: 'Asking whether a seat is free is answered by offering it.' },
  { ...quick(), prompt: '聞いて、いちばん　いい　返事を　選んで　ください。',
    narration: [{ speaker: 'woman', text: '傘、お持ちですか。降って　きましたよ。' }],
    options: ['あ、持って　きて　よかったです。', 'はい、降りました。', 'いいえ、傘です。', 'ええ、持ちません。'],
    note: 'A warning plus a question is answered about one’s own preparedness.' },
  { ...quick(), prompt: '聞いて、いちばん　いい　返事を　選んで　ください。',
    narration: [{ speaker: 'man', text: '今日は　これで　上がらせて　いただきます。' }],
    options: ['お疲れさまでした。', 'はい、上がりました。', 'いいえ、今日です。', 'ええ、これからです。'],
    note: 'Leaving ahead of others is answered with おつかれさまでした.' },
  { ...quick(), prompt: '聞いて、いちばん　いい　返事を　選んで　ください。',
    narration: [{ speaker: 'woman', text: 'もう　少し　安く　なりませんか。' }],
    options: ['申し訳ありません、これが　精一杯です。', 'はい、安く　なりました。', 'いいえ、少しです。', 'ええ、高いですね。'],
    note: 'A request for a discount is declined politely with a reason.' },
  { ...quick(), prompt: '聞いて、いちばん　いい　返事を　選んで　ください。',
    narration: [{ speaker: 'man', text: 'これ、手に　取って　見ても　いいですか。' }],
    options: ['はい、どうぞ　ご覧ください。', 'はい、見ました。', 'いいえ、手です。', 'ええ、取りました。'],
    note: 'Asking permission is granted and the speaker is directed where to go.' },
  { ...quick(), prompt: '聞いて、いちばん　いい　返事を　選んで　ください。',
    narration: [{ speaker: 'woman', text: '連休は　ゆっくり　できましたか。' }],
    options: ['ええ、家で　のんびり　しました。', 'はい、できます。', 'いいえ、連休です。', 'ええ、ゆっくりです。'],
    note: 'A past-tense question about the weekend takes a past-tense report.' },
  ],
  N2: [
{
    ...task(),
    prompt: '男の人は　このあと　まず　何を　しますか。',
    narration: [
      { speaker: 'narrator', text: '会社で　二人が　話しています。男の人は　このあと　まず　何を　しますか。', pauseAfter: 700 },
      { speaker: 'woman', text: '展示会の　申込書、今日が　締め切りですよ。', pauseAfter: 300 },
      { speaker: 'man', text: '書き終わっています。郵送しておきます。', pauseAfter: 300 },
      { speaker: 'woman', text: '郵送だと　間に合いません。窓口に　直接　出してください。', pauseAfter: 600 },
      { speaker: 'narrator', text: '男の人は　このあと　まず　何を　しますか。' },
    ],
    options: ['窓口に　申込書を　出す', '申込書を　郵送する', '申込書を　書き直す', '締め切りを　確認する'],
    note: 'The form is already written, so the task is delivery. Posting it is rejected on timing, which leaves the counter.',
  },
  {
    ...task(),
    prompt: '女の人は　このあと　何を　しますか。',
    narration: [
      { speaker: 'narrator', text: '会社で　二人が　話しています。女の人は　このあと　何を　しますか。', pauseAfter: 700 },
      { speaker: 'woman', text: '来客用の　資料、二十部　印刷しましょうか。', pauseAfter: 300 },
      { speaker: 'man', text: '参加者が　減ったので　十五部で　十分です。', pauseAfter: 300 },
      { speaker: 'woman', text: 'では　その　数で。表紙の　日付も　直しておきます。', pauseAfter: 600 },
      { speaker: 'narrator', text: '女の人は　このあと　何を　しますか。' },
    ],
    options: ['十五部　印刷する', '二十部　印刷する', '参加者に　連絡する', '表紙を　作り直す'],
    note: 'The number is corrected downward before she acts, so the revised figure is the answer.',
  },
  {
    ...task(),
    prompt: '二人は　まず　何を　しますか。',
    narration: [
      { speaker: 'narrator', text: '店で　二人が　話しています。二人は　まず　何を　しますか。', pauseAfter: 700 },
      { speaker: 'man', text: '棚の　商品を　並べ替えてから　値札を　貼りますか。', pauseAfter: 300 },
      { speaker: 'woman', text: '値札が　届くのは　午後です。先に　在庫を　数えましょう。', pauseAfter: 600 },
      { speaker: 'narrator', text: '二人は　まず　何を　しますか。' },
    ],
    options: ['在庫を　数える', '商品を　並べ替える', '値札を　貼る', '値札を　受け取る'],
    note: 'Both proposed tasks are blocked, and the third is what she substitutes.',
  },
  {
    ...task(),
    prompt: '女の人は　このあと　どこへ　行きますか。',
    narration: [
      { speaker: 'narrator', text: '会社で　二人が　話しています。女の人は　このあと　どこへ　行きますか。', pauseAfter: 700 },
      { speaker: 'woman', text: '工場の　見学、総務に　申し込めば　いいですか。', pauseAfter: 300 },
      { speaker: 'man', text: '申し込みは　総務ですが、先に　安全講習を　受けないと　受け付けてもらえません。', pauseAfter: 300 },
      { speaker: 'woman', text: '講習は　研修室ですね。そちらへ　行きます。', pauseAfter: 600 },
      { speaker: 'narrator', text: '女の人は　このあと　どこへ　行きますか。' },
    ],
    options: ['研修室', '総務', '工場', '受付'],
    note: 'The application is gated on the safety course, so the training room comes first.',
  },
  {
    ...task(),
    prompt: '男の人は　何を　持って　行きますか。',
    narration: [
      { speaker: 'narrator', text: '会社で　二人が　出張について　話しています。男の人は　何を　持って　行きますか。', pauseAfter: 700 },
      { speaker: 'woman', text: '出張には　契約書と　見本を　お願いします。', pauseAfter: 300 },
      { speaker: 'man', text: '契約書は　先方に　送付済みです。', pauseAfter: 300 },
      { speaker: 'woman', text: 'では　見本だけで。カタログは　現地に　あります。', pauseAfter: 600 },
      { speaker: 'narrator', text: '男の人は　何を　持って　行きますか。' },
    ],
    options: ['見本', '契約書', 'カタログ', '見本と　契約書'],
    note: 'Two of the three items are ruled out in turn, leaving only the samples.',
  },
  {
    ...task(),
    prompt: '女の人は　このあと　まず　何を　しますか。',
    narration: [
      { speaker: 'narrator', text: '会社で　二人が　話しています。女の人は　このあと　まず　何を　しますか。', pauseAfter: 700 },
      { speaker: 'man', text: 'システムの　不具合、利用者に　お知らせを　出しましょうか。', pauseAfter: 300 },
      { speaker: 'woman', text: '原因が　分からないまま　出すと　混乱します。', pauseAfter: 300 },
      { speaker: 'woman', text: '先に　開発担当に　状況を　確認します。', pauseAfter: 600 },
      { speaker: 'narrator', text: '女の人は　このあと　まず　何を　しますか。' },
    ],
    options: ['開発担当に　確認する', '利用者に　知らせる', 'システムを　止める', '原因を　公表する'],
    note: 'Announcing is postponed until the cause is known, so the check comes first.',
  },
  {
    ...point(),
    prompt: '男の人は　何が　問題だと　言って　いますか。',
    narration: [
      { speaker: 'narrator', text: '会社で　二人が　話しています。男の人は　何が　問題だと　言って　いますか。', pauseAfter: 700 },
      { speaker: 'woman', text: '新しい　受付システム、評判は　いいようですね。', pauseAfter: 300 },
      { speaker: 'man', text: '操作は　分かりやすいです。ただ、混雑時に　動きが　遅くなるんです。', pauseAfter: 600 },
      { speaker: 'narrator', text: '男の人は　何が　問題だと　言って　いますか。' },
    ],
    options: ['混雑時の　処理が　遅い　こと', '操作が　分かりにくい　こと', '評判が　よくない　こと', '費用が　高い　こと'],
    note: 'ただ introduces the single complaint after the interface is praised.',
  },
  {
    ...point(),
    prompt: '女の人は　どうして　予定を　変えましたか。',
    narration: [
      { speaker: 'narrator', text: '二人が　話しています。女の人は　どうして　予定を　変えましたか。', pauseAfter: 700 },
      { speaker: 'man', text: '旅行、天気が　心配で　延期したんですか。', pauseAfter: 300 },
      { speaker: 'woman', text: '天気は　問題ありません。宿が　改装中だと　後から　分かって。', pauseAfter: 600 },
      { speaker: 'narrator', text: '女の人は　どうして　予定を　変えましたか。' },
    ],
    options: ['宿が　使えなかったから', '天気が　悪かったから', '仕事が　忙しかったから', '料金が　上がったから'],
    note: 'The weather guess is denied outright; the reason follows immediately.',
  },
  {
    ...point(),
    prompt: '男の人は　何に　満足して　いますか。',
    narration: [
      { speaker: 'narrator', text: '二人が　引っ越しについて　話しています。男の人は　何に　満足して　いますか。', pauseAfter: 700 },
      { speaker: 'woman', text: '新しい　部屋、駅に　近くて　便利でしょう。', pauseAfter: 300 },
      { speaker: 'man', text: '駅までは　前より　遠いんです。でも　日当たりが　よくて　それが　気に入っています。', pauseAfter: 600 },
      { speaker: 'narrator', text: '男の人は　何に　満足して　いますか。' },
    ],
    options: ['日当たりが　よい　こと', '駅に　近い　こと', '家賃が　安い　こと', '部屋が　広い　こと'],
    note: 'The convenient-location assumption is corrected before the real merit is named.',
  },
  {
    ...point(),
    prompt: '女の人は　何を　心配して　いますか。',
    narration: [
      { speaker: 'narrator', text: '会社で　二人が　話しています。女の人は　何を　心配して　いますか。', pauseAfter: 700 },
      { speaker: 'man', text: '来月の　催し、予算は　足りそうですか。', pauseAfter: 300 },
      { speaker: 'woman', text: '予算は　確保できました。ただ、当日の　人手が　まだ　足りません。', pauseAfter: 600 },
      { speaker: 'narrator', text: '女の人は　何を　心配して　いますか。' },
    ],
    options: ['当日の　人手', '予算の　不足', '会場の　広さ', '天候の　悪化'],
    note: 'Budget is explicitly settled, so ただ marks the remaining worry.',
  },
  {
    ...point(),
    prompt: '男の人は　この　店の　何が　よいと　言って　いますか。',
    narration: [
      { speaker: 'narrator', text: '二人が　店について　話しています。男の人は　この　店の　何が　よいと　言って　いますか。', pauseAfter: 700 },
      { speaker: 'woman', text: 'あの　店、安いから　人気なんですか。', pauseAfter: 300 },
      { speaker: 'man', text: '値段は　普通です。注文してから　出てくるまでが　早いので　助かります。', pauseAfter: 600 },
      { speaker: 'narrator', text: '男の人は　この　店の　何が　よいと　言って　いますか。' },
    ],
    options: ['料理が　早く　出てくる　こと', '値段が　安い　こと', '店が　広い　こと', '場所が　便利な　こと'],
    note: 'Price is ranked as ordinary before the actual merit is given.',
  },
  {
    ...point(),
    prompt: '女の人は　何が　変わったと　言って　いますか。',
    narration: [
      { speaker: 'narrator', text: '会社で　二人が　話しています。女の人は　何が　変わったと　言って　いますか。', pauseAfter: 700 },
      { speaker: 'man', text: '勤務の　制度、始業時間が　変わったんですか。', pauseAfter: 300 },
      { speaker: 'woman', text: '始業は　同じです。在宅勤務の　申請が　要らなくなりました。', pauseAfter: 600 },
      { speaker: 'narrator', text: '女の人は　何が　変わったと　言って　いますか。' },
    ],
    options: ['在宅勤務の　申請が　不要に　なった', '始業時間が　早まった', '休日が　増えた', '通勤手当が　減った'],
    note: 'The first guess is denied, and the change named afterwards is the answer.',
  },
  {
    ...summary(),
    prompt: '話の　主な　内容は　何ですか。',
    narration: [
      { speaker: 'narrator', text: '会社で　担当者が　話しています。', pauseAfter: 600 },
      { speaker: 'woman', text: '来月から　会議室の　予約方法を　変更します。これまでは　前日までに　紙で　申請していただいていましたが、今後は　当日でも　端末から　予約できます。', pauseAfter: 300 },
      { speaker: 'woman', text: 'ただし、三十人以上の　大会議室だけは　これまでどおり　事前の　申請が　必要です。', pauseAfter: 700 },
      { speaker: 'narrator', text: '話の　主な　内容は　何ですか。' },
    ],
    options: ['会議室の　予約方法が　変わる　こと', '会議室が　新しく　増える　こと', '紙の　申請が　全て　なくなる　こと', '大会議室が　使えなく　なる　こと'],
    note: 'The talk announces a change of method, with one exception that does not change the main point.',
  },
  {
    ...summary(),
    prompt: '話の　主な　内容は　何ですか。',
    narration: [
      { speaker: 'narrator', text: '店長が　従業員に　話しています。', pauseAfter: 600 },
      { speaker: 'man', text: '最近、品切れの　問い合わせが　増えています。売れた　分を　その日の　うちに　記録していないことが　原因です。', pauseAfter: 300 },
      { speaker: 'man', text: '閉店後　五分で　構いませんので、必ず　その日の　数字を　入力してください。', pauseAfter: 700 },
      { speaker: 'narrator', text: '話の　主な　内容は　何ですか。' },
    ],
    options: ['売上を　その日の　うちに　記録して　ほしい　こと', '品切れの　商品を　増やす　こと', '閉店時間を　早める　こと', '問い合わせに　出ない　こと'],
    note: 'The cause is identified and a specific daily action is requested.',
  },
  {
    ...summary(),
    prompt: '話の　主な　内容は　何ですか。',
    narration: [
      { speaker: 'narrator', text: '講演で　女の人が　話しています。', pauseAfter: 600 },
      { speaker: 'woman', text: '読書量が　減ったと　言われますが、文字に　触れる　時間は　むしろ　増えています。', pauseAfter: 300 },
      { speaker: 'woman', text: '問題は　量ではなく、短い　文章ばかりを　読み、長い　筋道を　追う　機会が　減ったことです。', pauseAfter: 700 },
      { speaker: 'narrator', text: '話の　主な　内容は　何ですか。' },
    ],
    options: ['長い　文章を　読む　機会が　減って　いる　こと', '文字を　読む　時間が　減って　いる　こと', '読書が　不要に　なった　こと', '短い　文章の　方が　優れて　いる　こと'],
    note: 'The speaker rejects the usual framing and relocates the problem from quantity to the kind of reading.',
  },
  {
    ...summary(),
    prompt: '話の　主な　内容は　何ですか。',
    narration: [
      { speaker: 'narrator', text: '市の　説明会で　担当者が　話しています。', pauseAfter: 600 },
      { speaker: 'man', text: '駅前の　駐輪場を　来月から　有料に　します。無料だった　ため　長期間　放置される　自転車が　多く、使いたい　方が　止められない　状態でした。', pauseAfter: 300 },
      { speaker: 'man', text: '料金は　一日　百円とし、収入は　整備に　充てます。', pauseAfter: 700 },
      { speaker: 'narrator', text: '話の　主な　内容は　何ですか。' },
    ],
    options: ['駐輪場を　有料に　する　こと', '駐輪場を　なくす　こと', '自転車の　利用を　禁止する　こと', '駅前を　広げる　こと'],
    note: 'The announcement is a pricing change, with the abandonment problem as its reason.',
  },
  {
    ...summary(),
    prompt: '話の　主な　内容は　何ですか。',
    narration: [
      { speaker: 'narrator', text: '研修で　女の人が　話しています。', pauseAfter: 600 },
      { speaker: 'woman', text: '報告が　遅れる　方の　多くは、情報が　そろってから　伝えようと　しています。', pauseAfter: 300 },
      { speaker: 'woman', text: 'しかし　上司が　知りたいのは　完成した　報告ではなく、判断が　必要な　時点の　事実です。分からない　ことは　分からないまま　早く　伝えてください。', pauseAfter: 700 },
      { speaker: 'narrator', text: '話の　主な　内容は　何ですか。' },
    ],
    options: ['情報が　不完全でも　早く　報告する　こと', '報告は　完成してから　する　こと', '報告の　回数を　減らす　こと', '上司に　判断を　任せる　こと'],
    note: 'The speaker contrasts what reporters assume with what managers need, and asks for speed over completeness.',
  },
  {
    ...integrated(),
    prompt: '二人は　どう　する　ことに　しましたか。',
    narration: [
      { speaker: 'narrator', text: '会社で　二人が　社員旅行について　話しています。', pauseAfter: 600 },
      { speaker: 'man', text: '一泊に　すれば　参加しやすいですが、遠方は　選べません。', pauseAfter: 300 },
      { speaker: 'woman', text: '二泊なら　行き先は　広がりますが、休みが　取れない　人が　出ます。', pauseAfter: 300 },
      { speaker: 'man', text: '一泊を　基本に　して、希望者だけ　もう　一泊　延ばせるように　しては　どうでしょう。', pauseAfter: 300 },
      { speaker: 'woman', text: 'それなら　どちらの　人も　困りませんね。', pauseAfter: 700 },
      { speaker: 'narrator', text: '二人は　どう　する　ことに　しましたか。' },
    ],
    options: ['一泊を　基本に　し　希望者は　延泊できるように　する', '全員　一泊に　する', '全員　二泊に　する', '社員旅行を　取りやめる'],
    note: 'Neither plain option survives; the answer is the optional extension they build together.',
  },
  {
    ...integrated(),
    prompt: '二人は　どの　方法を　選びましたか。',
    narration: [
      { speaker: 'narrator', text: '会社で　二人が　問い合わせ対応について　話しています。', pauseAfter: 600 },
      { speaker: 'woman', text: '電話を　増やせば　早く　返せますが、人が　足りません。', pauseAfter: 300 },
      { speaker: 'man', text: 'メールだけに　すると　急ぎの　件が　埋もれます。', pauseAfter: 300 },
      { speaker: 'woman', text: 'よくある　質問を　先に　公開して、電話は　急ぎの　件に　絞っては。', pauseAfter: 300 },
      { speaker: 'man', text: '件数が　減れば　今の　人数でも　回りますね。', pauseAfter: 700 },
      { speaker: 'narrator', text: '二人は　どの　方法を　選びましたか。' },
    ],
    options: ['質問集を　公開し　電話は　急ぎだけに　する', '電話の　担当を　増やす', '問い合わせを　メールだけに　する', '問い合わせ対応を　やめる'],
    note: 'Reducing volume is what makes the existing staffing work, which neither first option did.',
  },
  {
    ...integrated(),
    prompt: '二人は　どう　する　ことに　しましたか。',
    narration: [
      { speaker: 'narrator', text: '店で　二人が　品ぞろえについて　話しています。', pauseAfter: 600 },
      { speaker: 'man', text: '種類を　増やせば　選べますが、売れ残りも　増えます。', pauseAfter: 300 },
      { speaker: 'woman', text: '絞れば　無駄は　減りますが、客が　離れます。', pauseAfter: 300 },
      { speaker: 'man', text: '定番は　常に　置き、季節物だけ　入れ替えては　どうでしょう。', pauseAfter: 300 },
      { speaker: 'woman', text: '新しさも　出せて　在庫も　抑えられますね。', pauseAfter: 700 },
      { speaker: 'narrator', text: '二人は　どう　する　ことに　しましたか。' },
    ],
    options: ['定番は　置き　季節物を　入れ替える', '種類を　大幅に　増やす', '種類を　大幅に　減らす', '季節物を　置かない'],
    note: 'The split keeps the range the customers want while limiting what can go unsold.',
  },
  {
    ...integrated(),
    prompt: '二人は　どの　案に　まとまりましたか。',
    narration: [
      { speaker: 'narrator', text: '会社で　二人が　新人研修について　話しています。', pauseAfter: 600 },
      { speaker: 'woman', text: '最初に　まとめて　教えると　現場で　忘れてしまいます。', pauseAfter: 300 },
      { speaker: 'man', text: '現場任せに　すると　教え方に　差が　出ます。', pauseAfter: 300 },
      { speaker: 'woman', text: '基本だけ　先に　教えて、残りは　月に　一度　集めて　補っては。', pauseAfter: 300 },
      { speaker: 'man', text: '差も　埋まり、忘れにくいですね。', pauseAfter: 700 },
      { speaker: 'narrator', text: '二人は　どの　案に　まとまりましたか。' },
    ],
    options: ['基本を　先に　教え　月に　一度　補う', '全部　最初に　教える', '全部　現場に　任せる', '研修を　行わない'],
    note: 'The periodic follow-up is what addresses both forgetting and inconsistency.',
  },
  { ...quick(), prompt: '聞いて、最も　よい　返事を　選んで　ください。',
    narration: [{ speaker: 'woman', text: 'この　件、私から　先方に　お伝えしておきましょうか。' }],
    options: ['助かります。お願いします。', 'はい、伝えておきました。', 'いいえ、先方です。', 'ええ、伝わりましたか。'],
    note: '～ましょうか offers to act, so the reply accepts or declines the offer.' },
  { ...quick(), prompt: '聞いて、最も　よい　返事を　選んで　ください。',
    narration: [{ speaker: 'man', text: 'あいにく　担当の　者が　席を　外しておりまして。' }],
    options: ['では　後ほど　かけ直します。', 'では　私が　外します。', 'はい、席に　います。', 'いいえ、担当です。'],
    note: 'The person is unavailable, so the natural reply is to call back later.' },
  { ...quick(), prompt: '聞いて、最も　よい　返事を　選んで　ください。',
    narration: [{ speaker: 'woman', text: 'その　案、もう　少し　検討させていただけませんか。' }],
    options: ['もちろんです。ご連絡　お待ちしています。', 'はい、検討しました。', 'いいえ、案です。', 'ええ、もう　少しです。'],
    note: 'A request for more time is granted, and the reply says what happens next.' },
  { ...quick(), prompt: '聞いて、最も　よい　返事を　選んで　ください。',
    narration: [{ speaker: 'man', text: '恐れ入りますが、こちらは　撮影禁止と　なっております。' }],
    options: ['失礼しました。すぐに　やめます。', 'はい、撮影します。', 'いいえ、禁止です。', 'ええ、こちらです。'],
    note: 'Being told a rule is met with an apology and compliance.' },
  { ...quick(), prompt: '聞いて、最も　よい　返事を　選んで　ください。',
    narration: [{ speaker: 'woman', text: '納期、何とか　前倒しできませんでしょうか。' }],
    options: ['社内で　確認して　ご返事します。', 'はい、前倒ししました。', 'いいえ、納期です。', 'ええ、何とかです。'],
    note: 'A difficult request is answered by promising to check, not by an immediate yes or no.' },
  { ...quick(), prompt: '聞いて、最も　よい　返事を　選んで　ください。',
    narration: [{ speaker: 'man', text: '先日は　わざわざ　お越しいただき　ありがとうございました。' }],
    options: ['こちらこそ　お世話に　なりました。', 'はい、越しました。', 'いいえ、わざわざです。', 'ええ、ありがとうです。'],
    note: 'Thanks are returned with こちらこそ rather than acknowledged literally.' },
  { ...quick(), prompt: '聞いて、最も　よい　返事を　選んで　ください。',
    narration: [{ speaker: 'woman', text: 'この　資料、部長に　お渡しいただけますか。' }],
    options: ['はい、確かに　お預かりします。', 'はい、渡していただきました。', 'いいえ、部長です。', 'ええ、資料でした。'],
    note: 'Being asked to pass something on is accepted with a word acknowledging receipt.' },
  { ...quick(), prompt: '聞いて、最も　よい　返事を　選んで　ください。',
    narration: [{ speaker: 'man', text: 'お支払いは　現金と　カード、どちらに　なさいますか。' }],
    options: ['カードで　お願いします。', 'はい、支払いました。', 'いいえ、どちらもです。', 'ええ、現金に　なります。'],
    note: 'A choice question is answered by picking one of the two options offered.' },
  { ...quick(), prompt: '聞いて、最も　よい　返事を　選んで　ください。',
    narration: [{ speaker: 'woman', text: '会議の　時間、十時からで　よろしかったでしょうか。' }],
    options: ['はい、十時で　結構です。', 'はい、よろしかったです。', 'いいえ、会議です。', 'ええ、時間でした。'],
    note: 'A confirmation question is answered by confirming the detail itself.' },
  ],
  N1: [
{
    ...task(),
    prompt: '男の人は　このあと　まず　何を　しますか。',
    narration: [
      { speaker: 'narrator', text: '会社で　二人が　統合の　準備について　話しています。男の人は　このあと　まず　何を　しますか。', pauseAfter: 650 },
      { speaker: 'woman', text: '両社の　顧客名簿を　突き合わせる　作業、今週中に　始められますか。', pauseAfter: 300 },
      { speaker: 'man', text: '着手は　できますが、個人情報の　取り扱いについて　合意が　まだです。', pauseAfter: 300 },
      { speaker: 'woman', text: 'それが　済むまでは　動かせません。法務に　確認を　取ってください。', pauseAfter: 650 },
      { speaker: 'narrator', text: '男の人は　このあと　まず　何を　しますか。' },
    ],
    options: ['法務に　取り扱いの　確認を　取る', '顧客名簿を　突き合わせる', '合意書を　作成する', '作業の　開始を　通知する'],
    note: 'The merge work is blocked on an unresolved agreement, so clearing it with legal comes first.',
  },
  {
    ...task(),
    prompt: '女の人は　このあと　何を　しますか。',
    narration: [
      { speaker: 'narrator', text: '編集部で　二人が　特集記事について　話しています。女の人は　このあと　何を　しますか。', pauseAfter: 650 },
      { speaker: 'man', text: '取材先から　写真の　使用許諾は　得られましたか。', pauseAfter: 300 },
      { speaker: 'woman', text: '口頭では　了解を　いただいています。', pauseAfter: 300 },
      { speaker: 'man', text: '口頭だけでは　後で　もめます。書面で　いただいておいてください。', pauseAfter: 650 },
      { speaker: 'narrator', text: '女の人は　このあと　何を　しますか。' },
    ],
    options: ['書面で　許諾を　もらう', '写真を　差し替える', '取材先に　謝罪する', '記事の　掲載を　見送る'],
    note: 'Verbal consent is treated as insufficient, and the instruction names the written form.',
  },
  {
    ...task(),
    prompt: '担当者は　まず　何を　しますか。',
    narration: [
      { speaker: 'narrator', text: '工場で　二人が　異音について　話しています。担当者は　まず　何を　しますか。', pauseAfter: 650 },
      { speaker: 'man', text: '三号機から　異音が　します。分解して　調べましょうか。', pauseAfter: 300 },
      { speaker: 'woman', text: '分解すると　原因の　状態が　分からなく　なります。', pauseAfter: 300 },
      { speaker: 'woman', text: '先に　稼働中の　音を　記録してください。', pauseAfter: 650 },
      { speaker: 'narrator', text: '担当者は　まず　何を　しますか。' },
    ],
    options: ['稼働中の　音を　記録する', '三号機を　分解する', '三号機を　止める', '部品を　交換する'],
    note: 'Dismantling would destroy the evidence, so recording the symptom precedes it.',
  },
  {
    ...task(),
    prompt: '男の人は　このあと　誰に　連絡しますか。',
    narration: [
      { speaker: 'narrator', text: '会社で　二人が　納入の　遅れについて　話しています。男の人は　このあと　誰に　連絡しますか。', pauseAfter: 650 },
      { speaker: 'man', text: '納入が　遅れそうです。お客様に　お詫びを　入れましょうか。', pauseAfter: 300 },
      { speaker: 'woman', text: '見通しが　立たないまま　謝ると　かえって　不信を　招きます。', pauseAfter: 300 },
      { speaker: 'man', text: 'では　輸送業者に　到着の　見込みを　確かめます。', pauseAfter: 650 },
      { speaker: 'narrator', text: '男の人は　このあと　誰に　連絡しますか。' },
    ],
    options: ['輸送業者', 'お客様', '工場', '上司'],
    note: 'Apologising is deferred until the arrival estimate exists, which fixes the order.',
  },
  {
    ...point(),
    prompt: '女の人は　何を　問題だと　考えて　いますか。',
    narration: [
      { speaker: 'narrator', text: '会議で　二人が　人事制度について　話しています。女の人は　何を　問題だと　考えて　いますか。', pauseAfter: 650 },
      { speaker: 'man', text: '評価の　回数が　少なすぎるという　ご指摘でしょうか。', pauseAfter: 300 },
      { speaker: 'woman', text: '回数は　十分です。問題は　評価の　根拠が　本人に　示されない　ことです。', pauseAfter: 650 },
      { speaker: 'narrator', text: '女の人は　何を　問題だと　考えて　いますか。' },
    ],
    options: ['評価の　根拠が　示されない　こと', '評価の　回数が　少ない　こと', '評価者が　不足して　いる　こと', '評価基準が　厳しすぎる　こと'],
    note: '問題は names the real issue after the frequency reading is set aside.',
  },
  {
    ...point(),
    prompt: '男の人は　何が　意外だったと　言って　いますか。',
    narration: [
      { speaker: 'narrator', text: '二人が　実験の　結果について　話しています。男の人は　何が　意外だったと　言って　いますか。', pauseAfter: 650 },
      { speaker: 'woman', text: '温度を　上げると　反応が　速く　なったという　ことですか。', pauseAfter: 300 },
      { speaker: 'man', text: 'それは　予想どおりでした。驚いたのは　一定の　温度を　超えると　逆に　遅く　なった　ことです。', pauseAfter: 650 },
      { speaker: 'narrator', text: '男の人は　何が　意外だったと　言って　いますか。' },
    ],
    options: ['高温では　反応が　遅く　なった　こと', '温度を　上げると　速く　なった　こと', '温度が　変わらなかった　こと', '反応が　起きなかった　こと'],
    note: '予想どおり marks the first item as expected, and 驚いたのは introduces the surprise.',
  },
  {
    ...point(),
    prompt: '女の人は　なぜ　反対して　いますか。',
    narration: [
      { speaker: 'narrator', text: '会議で　二人が　新店舗について　話しています。女の人は　なぜ　反対して　いますか。', pauseAfter: 650 },
      { speaker: 'man', text: '初期費用が　重いという　ことでしょうか。', pauseAfter: 300 },
      { speaker: 'woman', text: '費用は　回収できる　見込みです。ただ、既存店の　人員を　割く　ことに　なり、そちらが　回らなく　なります。', pauseAfter: 650 },
      { speaker: 'narrator', text: '女の人は　なぜ　反対して　いますか。' },
    ],
    options: ['既存店の　人員が　足りなく　なるから', '初期費用が　重いから', '立地が　悪いから', '需要が　見込めないから'],
    note: 'Cost is explicitly accepted before ただ isolates the staffing consequence.',
  },
  {
    ...point(),
    prompt: '男の人は　何を　評価して　いますか。',
    narration: [
      { speaker: 'narrator', text: '二人が　新しい　制度について　話しています。男の人は　何を　評価して　いますか。', pauseAfter: 650 },
      { speaker: 'woman', text: '手続きが　簡単に　なった　ところが　よいのですか。', pauseAfter: 300 },
      { speaker: 'man', text: '手続きは　むしろ　増えました。評価しているのは　判断の　理由が　記録に　残るように　なった　点です。', pauseAfter: 650 },
      { speaker: 'narrator', text: '男の人は　何を　評価して　いますか。' },
    ],
    options: ['判断の　理由が　記録に　残る　こと', '手続きが　簡単に　なった　こと', '費用が　下がった　こと', '人員が　増えた　こと'],
    note: 'The suggested merit is contradicted outright, and the real one follows 評価しているのは.',
  },
  {
    ...summary(),
    prompt: '話の　主な　内容は　何ですか。',
    narration: [
      { speaker: 'narrator', text: '講演で　男の人が　話しています。', pauseAfter: 600 },
      { speaker: 'man', text: '技術の　進歩は　選択肢を　増やしますが、増えた　分だけ　決めるのが　難しく　なります。', pauseAfter: 300 },
      { speaker: 'man', text: '必要なのは　さらに　多くの　情報ではなく、何を　捨てるかを　決める　基準です。基準の　ない　情報は　迷いを　増やすだけです。', pauseAfter: 700 },
      { speaker: 'narrator', text: '話の　主な　内容は　何ですか。' },
    ],
    options: ['選択には　何を　捨てるかの　基準が　要るという　こと', '情報を　もっと　集める　べきだという　こと', '技術の　進歩を　止める　べきだという　こと', '選択肢は　多い　ほど　よいという　こと'],
    note: 'The speaker rejects more information and relocates the need to a criterion for discarding.',
  },
  {
    ...summary(),
    prompt: '話の　主な　内容は　何ですか。',
    narration: [
      { speaker: 'narrator', text: '番組で　研究者が　話しています。', pauseAfter: 600 },
      { speaker: 'woman', text: '都市の　緑を　増やす　取り組みは　広がっていますが、面積だけを　指標に　する　例が　目立ちます。', pauseAfter: 300 },
      { speaker: 'woman', text: '同じ　面積でも、つながりの　ない　緑地は　生き物の　移動を　支えません。測るべきは　広さではなく　配置です。', pauseAfter: 700 },
      { speaker: 'narrator', text: '話の　主な　内容は　何ですか。' },
    ],
    options: ['緑地は　面積より　配置が　重要だという　こと', '緑地の　面積を　増やす　べきだという　こと', '都市に　緑地は　不要だという　こと', '生き物の　調査を　やめる　べきだという　こと'],
    note: 'The common metric is named and then replaced: the claim is about arrangement, not area.',
  },
  {
    ...summary(),
    prompt: '話の　主な　内容は　何ですか。',
    narration: [
      { speaker: 'narrator', text: '経営者が　話しています。', pauseAfter: 600 },
      { speaker: 'man', text: '失敗を　責めない　方針を　掲げる　会社は　増えました。しかし　掲げるだけでは　誰も　危険を　冒しません。', pauseAfter: 300 },
      { speaker: 'man', text: '実際に　失敗した　人が　その後　どう　扱われたか。社員が　見ているのは　方針ではなく　その　一点です。', pauseAfter: 700 },
      { speaker: 'narrator', text: '話の　主な　内容は　何ですか。' },
    ],
    options: ['社員は　方針より　失敗した　人の　扱いを　見て　いるという　こと', '失敗は　責める　べきだという　こと', '方針を　掲げれば　足りるという　こと', '挑戦は　避ける　べきだという　こと'],
    note: 'The stated policy is contrasted with the treatment that actually signals it.',
  },
  {
    ...integrated(),
    prompt: '二人は　どう　する　ことに　しましたか。',
    narration: [
      { speaker: 'narrator', text: '大学で　二人が　研究費の　配分について　話しています。', pauseAfter: 600 },
      { speaker: 'woman', text: '実績の　ある　研究に　重点配分すれば　成果は　確実ですが、新しい　芽が　育ちません。', pauseAfter: 300 },
      { speaker: 'man', text: '均等に　配ると　どの　研究も　中途半端に　終わります。', pauseAfter: 300 },
      { speaker: 'woman', text: '大半は　実績で　配分し、一部を　若手の　公募枠に　しては　どうでしょう。', pauseAfter: 300 },
      { speaker: 'man', text: '成果も　保ちつつ　新規性も　拾えますね。', pauseAfter: 700 },
      { speaker: 'narrator', text: '二人は　どう　する　ことに　しましたか。' },
    ],
    options: ['大半を　実績で　配分し　一部を　若手枠に　する', '全て　実績で　配分する', '全て　均等に　配分する', '配分を　凍結する'],
    note: 'Both pure rules are rejected; the reserved share is what rescues the new work.',
  },
  {
    ...integrated(),
    prompt: '二人は　どの　方針を　取りますか。',
    narration: [
      { speaker: 'narrator', text: '会社で　二人が　在宅勤務について　話しています。', pauseAfter: 600 },
      { speaker: 'man', text: '完全在宅に　すれば　通勤の　負担は　消えますが、新人が　育ちません。', pauseAfter: 300 },
      { speaker: 'woman', text: '全員　出社に　戻せば　遠方の　人が　辞めてしまいます。', pauseAfter: 300 },
      { speaker: 'man', text: '週に　一日だけ　全員が　そろう　日を　決めては　どうでしょう。', pauseAfter: 300 },
      { speaker: 'woman', text: '育成の　機会も　残り、負担も　抑えられますね。', pauseAfter: 700 },
      { speaker: 'narrator', text: '二人は　どの　方針を　取りますか。' },
    ],
    options: ['週に　一日　全員が　出社する　日を　作る', '完全在宅に　する', '全員　毎日　出社する', '在宅勤務を　廃止する'],
    note: 'One shared day is the minimum that preserves training without restoring the full burden.',
  },
  { ...quick(), prompt: '聞いて、最も　よい　返事を　選んで　ください。',
    narration: [{ speaker: 'man', text: 'ご指摘の　点、こちらの　確認不足でした。' }],
    options: ['いえ、こちらこそ　説明が　足りず　失礼しました。', 'はい、確認しておきました。', 'いいえ、指摘です。', 'ええ、不足して　おります。'],
    note: 'An admission of fault is met with a reciprocal softening, not agreement that they were at fault.' },
  { ...quick(), prompt: '聞いて、最も　よい　返事を　選んで　ください。',
    narration: [{ speaker: 'woman', text: '一存では　決めかねますので、持ち帰らせて　いただけますか。' }],
    options: ['もちろんです。ご検討　よろしく　お願いします。', 'はい、決めかねました。', 'いいえ、持ち帰りです。', 'ええ、一存です。'],
    note: 'A request to take it back for consideration is granted, with a closing request.' },
  { ...quick(), prompt: '聞いて、最も　よい　返事を　選んで　ください。',
    narration: [{ speaker: 'man', text: 'お差し支えなければ、理由を　伺っても　よろしいでしょうか。' }],
    options: ['ええ、構いません。実は　予算の　都合でして。', 'はい、差し支えました。', 'いいえ、理由です。', 'ええ、伺いました。'],
    note: 'Permission to ask is granted and the reason is supplied in the same breath.' },
  { ...quick(), prompt: '聞いて、最も　よい　返事を　選んで　ください。',
    narration: [{ speaker: 'woman', text: '今回ばかりは　見過ごす　わけには　まいりません。' }],
    options: ['おっしゃる　とおりです。処分を　検討します。', 'はい、見過ごします。', 'いいえ、今回です。', 'ええ、まいりません。'],
    note: 'A firm refusal to overlook is met with acceptance and a stated next step.' },
  { ...quick(), prompt: '聞いて、最も　よい　返事を　選んで　ください。',
    narration: [{ speaker: 'man', text: 'ご期待に　沿えず、誠に　申し訳　ございません。' }],
    options: ['いえ、事情は　承知しました。', 'はい、沿いました。', 'いいえ、期待です。', 'ええ、申し訳です。'],
    note: 'A formal apology is received by acknowledging the circumstances rather than denying them.' },
  { ...quick(), prompt: '聞いて、最も　よい　返事を　選んで　ください。',
    narration: [{ speaker: 'woman', text: 'その　件でしたら、前任者から　引き継いで　おります。' }],
    options: ['でしたら　話が　早いです。助かります。', 'はい、引き継ぎません。', 'いいえ、前任者です。', 'ええ、件でした。'],
    note: 'Learning the other party is already briefed is welcomed as saving time.' },
  { ...quick(), prompt: '聞いて、最も　よい　返事を　選んで　ください。',
    narration: [{ speaker: 'man', text: 'この　金額では　承服しかねます。' }],
    options: ['では　どの　あたりなら　ご検討　いただけますか。', 'はい、承服しました。', 'いいえ、金額です。', 'ええ、しかねます。'],
    note: 'A refusal framed as unavoidable invites a counter-question about acceptable terms.' },
  ],
};
