import type { Level, Token } from './course-data';

/**
 * Hand-authored 用法 and 言い換え類義.
 *
 * Both were generated in the wrong shape. 用法 offered the same sentence four
 * times with only the particle changed, which tests particles, not usage; the
 * real item gives four different sentences and asks which one uses the word
 * correctly. 言い換え類義 offered dictionary definitions ending in 〜こと, where the
 * real item replaces the underlined word with something that fits the sentence.
 */
export type UsageItem = {
  word: string;
  /** The sentence that uses the word correctly — always first; the app shuffles. */
  correct: string;
  /** Natural Japanese in which this word is the wrong choice. */
  wrong: [string, string, string];
  note: string;
};

export type ParaphraseItem = {
  sentence: Token[];
  answer: string;
  distractors: [string, string, string];
  note: string;
};

export const usageItems: Record<Level, UsageItem[]> = {
  N5: [],
  N4: [
    { word: '予定', correct: '来週の予定をまだ決めていません。',
      wrong: ['この電車は事故で予定しています。', '母に手紙の予定を書きました。', '駅までの予定は十分ぐらいです。'],
      note: '予定 is a plan or schedule. The others need 遅れて, 返事, and 時間.' },
    { word: '用意', correct: '出かける前にお弁当を用意しました。',
      wrong: ['この問題は難しくて用意できません。', '弟は毎日六時に用意します。', '駅の前で友だちを用意しています。'],
      note: '用意 is preparing things in advance. The others need 解決, 起き, and 待って.' },
    { word: '案内', correct: '受付の人が会議室まで案内してくれました。',
      wrong: ['母に旅行のお土産を案内しました。', 'この本は字が小さくて案内しにくい。', '寒いので窓を案内してください。'],
      note: '案内 is showing someone the way. The others need 渡し, 読み, and 閉めて.' },
    { word: '経験', correct: '外国で働いた経験があります。',
      wrong: ['この機械の経験がよくわかりません。', '今日は朝から経験がいいです。', '友だちに旅行の経験を借りました。'],
      note: '経験 is something you have lived through. The others need 使い方, 天気, and 本.' },
    { word: '遠慮', correct: '車内での通話はご遠慮ください。',
      wrong: ['駅までの道を遠慮してください。', 'この漢字の読み方を遠慮しました。', '友だちの家に遠慮を持って行きました。'],
      note: '遠慮 is refraining out of consideration. The others need 案内, 質問, and お土産.' },
    { word: '相談', correct: '進路について先生に相談しました。',
      wrong: ['遅れたことを相談して謝りました。', '新しい辞書を相談して買いました。', '荷物が重いので相談してもらった。'],
      note: '相談 is consulting someone about a problem. The others need 反省, 探して, and 手伝って.' },
    { word: '都合', correct: '来週の火曜日はご都合いかがですか。',
      wrong: ['この料理は都合がよくておいしい。', '駅から会社まで都合十五分かかります。', '子どもの都合が悪くて熱があります。'],
      note: '都合 is convenience of timing or circumstances. The others need 味, ちょうど, and 具合.' },
    { word: '説明', correct: '使い方を丁寧に説明してもらいました。',
      wrong: ['財布をなくしたので警察に説明しました。', 'このケーキは甘さを説明しています。', '毎朝六時に目覚まし時計が説明します。'],
      note: '説明 is explaining so someone understands. The others need 届け, 抑えて, and 鳴ります.' },
  ],
  N3: [
    { word: '確認', correct: '出発前に持ち物をもう一度確認した。',
      wrong: ['道が混んでいたので確認して遅れた。', '彼の意見に確認して手を挙げた。', 'この皿は割れやすいので確認に置いた。'],
      note: '確認 is checking that something is as expected. The others need 渋滞, 賛成, and 丁寧.' },
    { word: '我慢', correct: '痛みを我慢して最後まで走りきった。',
      wrong: ['この機械は古いので我慢が悪い。', '兄は妹に自分のケーキを我慢した。', '雨がやむまで駅で我慢していた。'],
      note: '我慢 is enduring something unpleasant. The others need 調子, 譲った, and 待って.' },
    { word: '募集', correct: '来月のイベントの参加者を募集しています。',
      wrong: ['落とした財布を町中で募集した。', '会議の資料を全員に募集した。', '古い写真をアルバムに募集した。'],
      note: '募集 is inviting people to apply or join. The others need 探した, 配った, and まとめた.' },
    { word: '提出', correct: '期限までにレポートを提出してください。',
      wrong: ['駅前に新しい店が提出しました。', '会議で新しい案を提出に反対した。', '暗いので電気を提出してください。'],
      note: '提出 is handing in a document. The others need できました, 出す案, and つけて.' },
    { word: '反省', correct: '準備不足だったと反省している。',
      wrong: ['一年の予定を反省して手帳に書いた。', '彼の説明を反省してから質問した。', '古い写真を見て昔を反省した。'],
      note: '反省 is looking critically at your own conduct. The others need 計画, 理解, and 懐かしんだ.' },
    { word: '影響', correct: '台風の影響で電車が止まっている。',
      wrong: ['この薬は水と一緒に影響してください。', '彼は会議で強い影響を言った。', '窓からの影響が強くてまぶしい。'],
      note: '影響 is an effect one thing has on another. The others need 服用, 意見, and 日差し.' },
    { word: '応援', correct: '母校のチームを応援しに行った。',
      wrong: ['荷物が重いので応援して運んだ。', '知らない言葉を辞書で応援した。', '傘を忘れたので友だちに応援した。'],
      note: '応援 is cheering someone on. The others need 手伝って, 調べた, and 借りた.' },
    { word: '延期', correct: '雨のため運動会は来週に延期された。',
      wrong: ['会議の時間を三十分延期して短くした。', '契約の期限を延期に守れなかった。', '電車が遅れて到着が延期した。'],
      note: '延期 postpones an event to a later date. The others need 短縮, 期限内, and 遅れた.' },
  ],
  N2: [
    { word: '促進', correct: '自治体は公共交通の利用を促進している。',
      wrong: ['会議の開始時刻を促進してほしい。', '彼は毎朝の運動を促進して健康になった。', '古い規則を促進して新しくした。'],
      note: '促進 is encouraging something to progress. The others need 早めて, 継続, and 改めて.' },
    { word: '検討', correct: '委員会は制度の見直しを検討している。',
      wrong: ['落とし物の持ち主を検討している。', '実験の結果を検討に発表した。', '道具を検討して棚にしまった。'],
      note: '検討 is examining a matter before deciding. The others need 探して, 慎重に, and 整理して.' },
    { word: '把握', correct: '現場の状況を正確に把握しておきたい。',
      wrong: ['荷物をしっかり把握して運んだ。', '会議の日程を把握に変更した。', '彼の手を把握して励ました。'],
      note: '把握 is grasping a situation mentally, not physically. The others need 持って, 急に, and 握って.' },
    { word: '徹底', correct: '安全管理を徹底するよう指示が出た。',
      wrong: ['この道は徹底して細いので注意が必要だ。', '議論が徹底して結論が出なかった。', '彼は徹底を尽くして走り続けた。'],
      note: '徹底 is carrying something through thoroughly. The others need 非常に, 紛糾, and 全力.' },
    { word: '発揮', correct: '本番で実力を十分に発揮できた。',
      wrong: ['新しい商品を市場に発揮した。', '意見を大きな声で発揮した。', '会場の照明を明るく発揮した。'],
      note: '発揮 is demonstrating ability you already have. The others need 投入, 主張, and 調整.' },
    { word: '配慮', correct: '子ども連れの方にも配慮した席を用意した。',
      wrong: ['資料を全員に配慮してください。', '予算を各部署に配慮して分けた。', '荷物を棚の上に配慮した。'],
      note: '配慮 is thoughtful consideration for others. The others need 配布, 配分, and 置いた.' },
    { word: '訂正', correct: '記事の誤りを訂正してお詫びした。',
      wrong: ['服の汚れを訂正してから出かけた。', '曲がった道を訂正して進んだ。', '弟の態度を訂正して叱った。'],
      note: '訂正 is correcting an error in what was stated or written. The others need 落として, まっすぐ, and 改めさせて.' },
    { word: '削減', correct: '経費を二割削減する方針が決まった。',
      wrong: ['原稿の誤字を削減して直した。', '会議の参加者を削減して集めた。', '荷物の重さを削減に感じた。'],
      note: '削減 is cutting an amount or cost. The others need 訂正, 絞って, and 軽く.' },
  ],
  N1: [
    { word: '一括', correct: '費用は分割ではなく一括で支払った。',
      wrong: ['資料を一括に読んで理解した。', '彼は一括して意見を述べたが賛成しなかった。', '荷物を一括に持ち上げた。'],
      note: '一括 means handling things together in a single lot. The others need 一気に, 一貫, and 一度に.' },
    { word: '是正', correct: '地域間の格差を是正する必要がある。',
      wrong: ['書類の誤字を是正して提出した。', '曲がった柱を是正して立て直した。', '彼の遅刻を是正して注意した。'],
      note: '是正 corrects a structural wrong such as an imbalance. The others need 訂正, まっすぐに, and 咎めて.' },
    { word: '網羅', correct: 'この事典は主要な用語を網羅している。',
      wrong: ['犯人を網羅して逮捕した。', '会場に人が網羅していた。', '意見を網羅して一つに決めた。'],
      note: '網羅 is covering a field exhaustively. The others need 追い詰めて, 密集, and 集約.' },
    { word: '打開', correct: '行き詰まった交渉を打開する案が求められている。',
      wrong: ['固い瓶のふたを打開して開けた。', '新しい市場を打開して進出した。', '古い建物を打開して取り壊した。'],
      note: '打開 is breaking through a deadlock. The others need こじ開けて, 開拓, and 解体.' },
    { word: '逸脱', correct: '議論が本来の目的から逸脱している。',
      wrong: ['彼は列から逸脱して走り出した。', '契約の期限を逸脱してしまった。', '成績が平均を逸脱して高い。'],
      note: '逸脱 is straying from a norm or purpose. The others need 抜け出して, 過ぎて, and 上回って.' },
    { word: '還元', correct: '利益の一部を地域に還元する取り組みだ。',
      wrong: ['借りた本を図書館に還元した。', '故障した部品を新しいものに還元した。', '古い写真の色を還元して直した。'],
      note: '還元 is returning gains to those who generated them. The others need 返却, 交換, and 復元.' },
    { word: '誘致', correct: '市は国際会議の誘致に成功した。',
      wrong: ['友人を食事に誘致した。', '子どもを危険な場所から誘致した。', '客の注意を商品に誘致した。'],
      note: '誘致 is attracting an institution or event to a locality. The others need 誘った, 遠ざけた, and 引きつけた.' },
    { word: '抜粋', correct: '報告書から要点を抜粋して配布した。',
      wrong: ['庭の雑草を抜粋して片づけた。', '候補者の中から一人を抜粋した。', '古い記録を抜粋して捨てた。'],
      note: '抜粋 is extracting passages from a text. The others need 抜いて, 選出, and 処分.' },
  ],
};

export const paraphraseItems: Record<Level, ParaphraseItem[]> = {
  N5: [
    { sentence: ['この　もんだいは　', { kanji: 'かんたん', reading: '', target: true }, 'です。'],
      answer: 'やさしい', distractors: ['むずかしい', 'たいせつ', 'ゆうめい'], note: 'かんたん ≒ やさしい (easy). むずかしい is its opposite.' },
    { sentence: ['きのうは　', { kanji: 'おおぜい', reading: '', target: true }, 'の　人が　きました。'],
      answer: 'たくさん', distractors: ['すこし', 'ひとり', 'だれも'], note: 'おおぜい ≒ たくさん, and is used only for people.' },
    { sentence: ['この　みちは　', { kanji: 'あぶない', reading: '', target: true }, 'です。'],
      answer: 'きけん', distractors: ['あんぜん', 'しずか', 'べんり'], note: 'あぶない ≒ きけん. あんぜん is the opposite.' },
    { sentence: ['しゅくだいは　', { kanji: 'ぜんぶ', reading: '', target: true }, 'おわりました。'],
      answer: 'すべて', distractors: ['はんぶん', 'すこし', 'まだ'], note: 'ぜんぶ ≒ すべて (all of it).' },
    { sentence: ['この　みせは　いつも　', { kanji: 'すいて', reading: '', target: true }, 'います。'],
      answer: '人が　すくない', distractors: ['人が　おおい', 'しまって　いる', 'たかい'], note: 'すいている means uncrowded — few people.' },
    { sentence: ['きょうは　', { kanji: 'ひま', reading: '', target: true }, 'です。'],
      answer: 'じかんが　ある', distractors: ['いそがしい', 'つかれた', 'たのしい'], note: 'ひま ≒ having free time; いそがしい is the opposite.' },
    { sentence: ['その　はなしは　', { kanji: 'ほんとう', reading: '', target: true }, 'ですか。'],
      answer: 'うそでは　ない', distractors: ['おもしろい', 'ながい', 'あたらしい'], note: 'ほんとう asks whether something is true, so the match is うそではない. The other three describe the story rather than its truth.' },
    { sentence: ['へやを　', { kanji: 'きれいに', reading: '', target: true }, 'しました。'],
      answer: 'そうじ', distractors: ['よごれた', 'ひろく', 'あたたかく'], note: 'きれいにする a room ≒ cleaning it.' },
  ],
  N4: [
    { sentence: ['この　へやは　', { kanji: 'ずいぶん', reading: '', target: true }, '　ひろいですね。'],
      answer: 'とても', distractors: ['すこし', 'あまり', 'ぜんぜん'], note: 'ずいぶん ≒ とても. It strengthens the adjective, unlike すこし.' },
    { sentence: ['かれは　', { kanji: 'たいてい', reading: '', target: true }, '　七時に　起きます。'],
      answer: 'ほとんど　いつも', distractors: ['ときどき', 'めったに', 'かならず'], note: 'たいてい means usually — not always (かならず) and not occasionally.' },
    { sentence: ['この　仕事は　', { kanji: '大変', reading: 'たいへん', target: true }, 'です。'],
      answer: 'とても　むずかしい', distractors: ['かんたんだ', 'つまらない', 'めずらしい'], note: '大変 here means demanding, not "terrible".' },
    { sentence: ['かのじょは　', { kanji: 'ふだん', reading: '', target: true }, '　電車で　通っています。'],
      answer: 'いつもは', distractors: ['きのうは', 'たまに', 'これから'], note: 'ふだん ≒ ordinarily, as a habit.' },
    { sentence: ['この　道具は　', { kanji: '役に立つ', reading: 'やくにたつ', target: true }, '。'],
      answer: 'べんりだ', distractors: ['こわれやすい', 'たかい', 'めずらしい'], note: '役に立つ means useful, so べんり is the match. こわれやすい and たかい are about the tool but not about its usefulness.' },
    { sentence: ['かれは　', { kanji: 'まじめ', reading: '', target: true }, 'な　学生です。'],
      answer: 'よく　勉強する', distractors: ['よく　休む', 'おもしろい', 'しずかな'], note: 'まじめ describes someone earnest and diligent.' },
    { sentence: ['この　店は　', { kanji: 'めずらしい', reading: '', target: true }, '　物を　売って　います。'],
      answer: 'あまり　見ない', distractors: ['よく　見る', 'やすい', 'ふるい'], note: 'めずらしい ≒ rarely seen.' },
    { sentence: ['きゅうに　雨が　', { kanji: 'ふりだした', reading: '', target: true }, '。'],
      answer: 'ふりはじめた', distractors: ['やんだ', 'つよく　なった', 'よわく　なった'], note: '～だす ≒ ～はじめる: the action starts.' },
  ],
  N3: [
    { sentence: [{ kanji: 'うっかり', reading: '', target: true }, '　約束を　忘れて　しまった。'],
      answer: '不注意で', distractors: ['わざと', '完全に', '運よく'], note: 'うっかり is carelessly, without noticing — never deliberate.' },
    { sentence: ['その　話は　', { kanji: 'いちおう', reading: '', target: true }, '　聞いて　おいた。'],
      answer: 'とりあえず', distractors: ['くわしく', '何度も', 'まったく'], note: 'いちおう ≒ for the time being, not thoroughly.' },
    { sentence: ['かれは　', { kanji: 'あいかわらず', reading: '', target: true }, '　忙しそうだ。'],
      answer: '前と　同じように', distractors: ['めずらしく', '急に', 'ようやく'], note: 'あいかわらず ≒ as always, unchanged.' },
    { sentence: ['この　計画は　', { kanji: 'そうとう', reading: '', target: true }, '　むずかしい。'],
      answer: 'かなり', distractors: ['わずかに', 'まったく', 'いくらか'], note: 'そうとう ≒ considerably.' },
    { sentence: ['かのじょは　', { kanji: 'あわてて', reading: '', target: true }, '　部屋を　出て　行った。'],
      answer: '急いで', distractors: ['ゆっくり', 'しずかに', 'よろこんで'], note: 'あわてる is hurrying in a flustered way.' },
    { sentence: ['その　案は　', { kanji: 'ようやく', reading: '', target: true }, '　認められた。'],
      answer: 'やっと', distractors: ['すぐに', '簡単に', '突然'], note: 'ようやく ≒ やっと — at long last.' },
    { sentence: ['かれの　説明は　', { kanji: 'あいまい', reading: '', target: true }, 'だった。'],
      answer: 'はっきりしない', distractors: ['くわしい', '正しい', '長い'], note: 'あいまい ≒ vague, unclear.' },
    { sentence: ['この　仕事を　', { kanji: 'ひきうけた', reading: '', target: true }, '。'],
      answer: '引き受ける　ことに　した', distractors: ['ことわった', 'やめた', '手伝った'], note: '引き受ける is taking a task on, the opposite of 断る.' },
  ],
  N2: [
    { sentence: ['この　計画は　', { kanji: '大幅', reading: 'おおはば', target: true }, 'に　変更された。'],
      answer: '大きく', distractors: ['わずかに', '突然', 'ひそかに'], note: '大幅に is by a large margin — about extent, not speed or secrecy.' },
    { sentence: ['かれは　', { kanji: 'しばしば', reading: '', target: true }, '　遅刻する。'],
      answer: 'たびたび', distractors: ['まれに', '一度だけ', '決して'], note: 'しばしば ≒ たびたび (frequently).' },
    { sentence: ['その　主張には　', { kanji: '根拠', reading: 'こんきょ', target: true }, 'が　ない。'],
      answer: '裏づけ', distractors: ['興味', '価値', '期限'], note: '根拠 ≒ the evidence backing a claim.' },
    { sentence: ['会議は　', { kanji: '円滑', reading: 'えんかつ', target: true }, 'に　進んだ。'],
      answer: 'スムーズ', distractors: ['慎重', '活発', '静か'], note: '円滑 ≒ smoothly, without friction.' },
    { sentence: ['かれの　説明は　', { kanji: '的確', reading: 'てきかく', target: true }, 'だった。'],
      answer: '要点を　外さない', distractors: ['まわりくどい', '長すぎる', 'あいまいな'], note: '的確 ≒ precisely on point.' },
    { sentence: ['この　制度は　', { kanji: 'ほぼ', reading: '', target: true }, '　定着した。'],
      answer: 'だいたい', distractors: ['まったく', 'わずかに', 'かろうじて'], note: 'ほぼ ≒ almost entirely.' },
    { sentence: ['費用を　', { kanji: '負担', reading: 'ふたん', target: true }, 'する　ことに　なった。'],
      answer: '引き受けて　払う', distractors: ['受け取る', '計算する', '節約する'], note: '負担する is bearing a cost, not receiving or calculating it.' },
    { sentence: ['その　可能性は　', { kanji: '極めて', reading: 'きわめて', target: true }, '　低い。'],
      answer: '非常に', distractors: ['やや', 'それほど', 'まったく'], note: '極めて ≒ 非常に — an intensifier.' },
  ],
  N1: [
    { sentence: ['その　提案は　', { kanji: 'あっけなく', reading: '', target: true }, '　退けられた。'],
      answer: '簡単に', distractors: ['慎重に', '全員一致で', 'しぶしぶ'], note: 'あっけなく is over far more easily than expected.' },
    { sentence: ['両者の　主張は　', { kanji: '相容れない', reading: 'あいいれない', target: true }, '。'],
      answer: '両立しない', distractors: ['よく　似ている', '関係が　ない', '補い合う'], note: '相容れない means the two cannot both hold.' },
    { sentence: ['かれは　責任を　', { kanji: '一手に', reading: 'いってに', target: true }, '　引き受けた。'],
      answer: '一人で　すべて', distractors: ['他人と　分けて', '形式的に', 'しぶしぶ'], note: '一手に引き受ける is taking the whole thing on alone.' },
    { sentence: ['この　結果は　', { kanji: '示唆', reading: 'しさ', target: true }, 'に　富む。'],
      answer: '考える　手がかりが　多い', distractors: ['疑わしい', '単純で　明快だ', '前例が　ない'], note: '示唆に富む means rich in hints worth thinking about.' },
    { sentence: ['議論は　', { kanji: '平行線', reading: 'へいこうせん', target: true }, 'を　たどった。'],
      answer: '歩み寄りが　なかった', distractors: ['すぐに　まとまった', '中止に　なった', '盛り上がった'], note: '平行線をたどる: neither side moves closer.' },
    { sentence: ['その　説明は　', { kanji: '腑に落ちない', reading: 'ふにおちない', target: true }, '。'],
      answer: '納得できない', distractors: ['よく　わかる', '長すぎる', '正確だ'], note: '腑に落ちない is failing to sit right with you.' },
    { sentence: ['計画は　', { kanji: '頓挫', reading: 'とんざ', target: true }, 'した。'],
      answer: '途中で　行き詰まった', distractors: ['予定どおり　進んだ', '前倒しに　なった', '規模が　拡大した'], note: '頓挫する: the project stalls partway.' },
    { sentence: ['かれの　態度は　', { kanji: '一貫', reading: 'いっかん', target: true }, 'して　いる。'],
      answer: '始めから　終わりまで　変わらない', distractors: ['場合に　よって　変わる', 'はっきりしない', '厳しすぎる'], note: '一貫している: consistent throughout.' },
  ],
};
